#############################################################################
##
##  alpha-complete.g  --  Level 3: the COMPLETE determination of all chiral
##  or directly regular skeletal 4-polytopes in E^4 whose cells are PETCOX
##  polyhedra H_alpha(T), over ALL isometries of E^4 (no parent group).
##
##  The three theorems used (proofs in theory.md, Section E):
##
##   E1  The base vertex lies on the PETCOX circle Pi = Fix(S2) = span(v0,v3)
##       (Prop. B2), and for each base vertex w on that circle there is
##       EXACTLY ONE isometry X with (S2X)^2 = (S1S2X)^2 = 1 fixing w, namely
##       X_w = S2^-1 A_w with A_w the half-turn about span(w_1, w_2), where
##       w = w_1 + w_2 is the decomposition into the invariant planes of the
##       twist S1.  (Degenerate exception: w in one of the invariant planes,
##       which makes the 2-face planar; those w are computed too.)
##
##   E2  The vertex-figure group <S2, X> fixes w, hence lies in the SO(3) of
##       the 3-space w^perp; being finite and generated by two rotations of
##       orders q, m >= 3 whose product is an involution, and satisfying
##       <S2> cap <X> = 1, it is A4, S4 or A5.  Hence
##             m = ord(X) in {3, 4, 5}
##       and the vertex-figure is a Platonic solid.
##
##   E3  X_w fixes the base edge pointwise, so it is the identity on the plane
##       span(w, w S1^-1) and a rotation by theta on the orthogonal plane;
##       hence tr(X_w) = 2 + 2 cos(theta) (plus 1 in the 5-dimensional
##       simplex coordinates), and ord(X_w) = m forces
##             tr(X_w) = 2 + 2 cos(2 pi k / m),   gcd(k,m) = 1, 1 <= k <= m/2.
##
##  Writing the base vertex projectively as w(t) = t v0 + v3 (t in R u {oo};
##  t = oo is w = v0, i.e. alpha = 0), the matrix A_{w(t)} is a rational
##  function of t with denominator d1(t) d2(t) (d_i = |w_i|^2), so each
##  condition of E3 becomes a polynomial equation of degree <= 4 in t, solved
##  here EXACTLY (factorisation over Q(sqrt 5), roots in cyclotomic fields).
##  Every root is then tested completely.  This settles Level 3 for all ten
##  PETCOX families.
##
##  Run from gap/:   gap -q -A --quitonbreak alpha-complete.g < /dev/null
##
#############################################################################

if not IsBound(PX) then Read("lib.g"); fi;
if not IsBound(PX.T) or Length(RecNames(PX.T)) = 0 then Read("polytopes.g"); PX.BuildAll(); PX.SetupRows(); fi;

PX.AlphaTSV := "../logs/alpha-complete-rows.tsv";
PrintTo(PX.AlphaTSV, JoinStringsWithSeparator([
  "case_id","T","m_target","k","t","alpha","alpha_numeric","X_order","vertex_figure_group","relations",
  "intersection_condition","ip_defect","fvector","directly_regular","faithful","skeletal_polytope",
  "geometrically_chiral","classification","note"], "\t"), "\n");

PX.AlphaSaved := "../logs/alpha-survivors.g";
PrintTo(PX.AlphaSaved, "# machine-generated by alpha-complete.g: every faithful skeletal 4-polytope found at Level 3\n",
        "if not IsBound(PX.Saved) then PX.Saved := []; fi;\n");

t := Indeterminate(CF(5), "t");
PX.AlphaResultsComplete := rec();
PX.AllRoots := [];

## targets: (m, k) with gcd(k,m) = 1, 1 <= k <= m/2, m in {3,4,5}.  By
## Prop. E2 the vertex-figure group <S2,X> is A4, S4 or A5, so the triple
## (2, q, m) must be a spherical triangle: 1/2 + 1/q + 1/m > 1.  Hence
##      q = 3  =>  m in {3,4,5};      q = 4 or 5  =>  m = 3.
PX.AllTargets := [ rec(m := 3, k := 1), rec(m := 4, k := 1), rec(m := 5, k := 1), rec(m := 5, k := 2) ];
PX.TargetsFor := function(q)
  return Filtered(PX.AllTargets, tg -> 1/2 + 1/q + 1/tg.m > 1);
end;
## Element orders of [3,3,5]^+ = +-[I x I], needed for the icosahedral
## obstruction (Prop. E4): if 5 is in {q, m} then the vertex-figure group is
## A5, which lifts to a diagonal copy of the binary icosahedral group 2I, so
## both quaternionic projections of Gamma contain 2I; 2I is maximal among the
## finite subgroups of S^3, so Gamma is conjugate into (2I x 2I)/{+-1} =
## [3,3,5]^+ whenever Gamma is finite.  An S1 whose order is not an element
## order of [3,3,5]^+ therefore rules the case out completely.
PX.H335plus := function()
  local T, S, ps;
  T := PX.T.("{3,3,5}");
  ps := PX.PermSetup(T.W);
  return Subgroup(ps.P, [ps.im(T.R[1]*T.R[2]), ps.im(T.R[2]*T.R[3]), ps.im(T.R[3]*T.R[4])]);
end;
PX.OrdersH335 := Set(List(ConjugacyClasses(PX.H335plus()), c -> Order(Representative(c))));
Print("element orders of [3,3,5]^+ (order ", Size(PX.H335plus()), "): ", PX.OrdersH335, "\n");
## +-[O x O] = the rotation subgroup of [[3,4,3]] (order 2304), of order 1152
PX.OOgroup := function()
  local Tc, F4, D, FF4, ps, els;
  Tc := PX.T.("{4,3,3}");
  F4 := Group(Concatenation(Tc.R, [PX.Reflection([1,1,1,1])]));
  D := (1/PX.SqrtCyc(2))*[[1,1,0,0],[1,-1,0,0],[0,0,1,1],[0,0,1,-1]];
  FF4 := Group(Concatenation(GeneratorsOfGroup(F4), [D]));
  els := Filtered(AsList(FF4), x -> DeterminantMat(x) = 1);
  return rec(order := Length(els), orders := Set(List(els, Order)));
end;
PX.OO := PX.OOgroup();
PX.OrdersOO := PX.OO.orders;
Print("element orders of +-[O x O] (order ", PX.OO.order, "): ", PX.OrdersOO, "\n");

PX.AnalyseRow := function(name)
  local T, S, S1, S2, d, I, planes, wpol, w1, w2, d1, d2, dh, N, terms, pl, wi, tau, res, tg, c, poly,
        sol, r, root, w, u, alpha, fields, deg, kk, vfg, ip, ps, s, full, fields2, cid, cnt, classification,
        note, fv, ident, canon, dsq, hyp, base, extra, sg, q, targets, ab, killed, cf, g;
  T := PX.T.(name);
  S := PX.CanonicalTriple(T); S1 := S[1]; S2 := S[2];
  d := T.dim; I := IdentityMat(d);
  Print("\n\n############################################################\n");
  Print("## Level 3 for T = ", name, "   (dim ", d, ")\n");
  Print("############################################################\n");
  planes := PX.Eigenplanes(S1, T.hyper);
  Print("invariant planes of S1 (order ", Order(S1), "): rotation indices k = ", List(planes, x -> x.k),
        " of ", Order(S1), "  (twist type from the census: ", PX.Table[PX.RowOf.(name)].type, ")\n");
  PX.CHECKEQ(Concatenation(name, ": S1 has exactly two invariant planes"), Length(planes), 2);
  PX.CHECK(Concatenation(name, ": the two rotation angles are distinct and non-opposite (theta2 <> +- theta1)"),
           planes[1].k <> planes[2].k and (planes[1].k + planes[2].k) mod Order(S1) <> 0);
  ## the two planes are orthogonal and span the 4-space
  PX.CHECK(Concatenation(name, ": the invariant planes are mutually orthogonal"),
           ForAll(planes[1].basis, a -> ForAll(planes[2].basis, b -> a*b = 0)));
  ## the PETCOX circle meets an invariant plane?  (degenerate, planar 2-face)
  for pl in planes do
    ## Pi cap E_i:  solutions (a,b) with a v0 + b v3 in E_i  <=>  (a v0 + b v3)(I - P) = 0
    hyp := NullspaceMat([T.v0*(I - pl.P), T.v3*(I - pl.P)]);
    Print("circle cap (invariant plane k = ", pl.k, "): dimension ", Length(hyp));
    if Length(hyp) > 0 then Print("  -> DEGENERATE base vertices (a,b) = ", hyp); fi;
    Print("\n");
    PX.CHECK(Concatenation(name, ": the PETCOX circle avoids the invariant plane k = ", String(pl.k),
             " (no planar 2-face)"), Length(hyp) = 0);
  od;
  ## w(t) = t v0 + v3
  wpol := List([1..d], i -> t*T.v0[i] + T.v3[i]);
  w1 := wpol*planes[1].P;  w2 := wpol*planes[2].P;
  d1 := w1*w1;  d2 := w2*w2;
  Print("degrees: d1 = ", DegreeOfLaurentPolynomial(d1), ", d2 = ", DegreeOfLaurentPolynomial(d2), "\n");
  ## N(t) = 2( w1^T w1 d2 dh + w2^T w2 d1 dh + h^T h d1 d2 ) - d1 d2 dh I,  A = N/(d1 d2 dh)
  if T.hyper <> fail then dh := T.hyper*T.hyper; else dh := One(CF(5)); fi;
  N := 2*( TransposedMat([w1])*[w1]*d2*dh + TransposedMat([w2])*[w2]*d1*dh );
  if T.hyper <> fail then
    N := N + 2*TransposedMat([T.hyper])*[T.hyper]*d1*d2;
  fi;
  N := N - d1*d2*dh*IdentityMat(d);
  tau := Trace(S2^-1 * N);
  Print("tr(X(t)) = tau(t)/(d1 d2", Concatenation(" ", String(dh <> One(CF(5)))), "), deg tau = ",
        DegreeOfLaurentPolynomial(tau), "\n");
  res := rec(name := name, planes := planes, roots := [], unresolved := [], hard := []);
  cnt := 0;
  q := Order(S2);
  targets := PX.TargetsFor(q);
  Print("q = ord(S2) = ", q, "; admissible orders m = ord(X) by the spherical-triangle condition: ",
        Set(List(targets, x -> x.m)), " (excluded: ", Set(List(Filtered(PX.AllTargets, x -> not x in targets), x -> x.m)),
        ", because 1/2 + 1/q + 1/m <= 1 makes <S2,X> infinite, contradicting Prop. E2)\n");
  for tg in PX.AllTargets do
    if not tg in targets then
      Print("\n-- target ord(X) = ", tg.m, " (k = ", tg.k, "): EXCLUDED a priori (1/2 + 1/", q, " + 1/", tg.m, " <= 1)\n");
      continue;
    fi;
    ## Prop. E4: order obstruction from the quaternionic projections
    if (tg.m = 5 or q = 5) and not Order(S1) in PX.OrdersH335 then
      Print("\n-- target ord(X) = ", tg.m, " (k = ", tg.k, "): EXCLUDED a priori: the vertex-figure group would be A5, ",
            "forcing Gamma <= [3,3,5]^+ (order 7200), which has no element of order ", Order(S1), " = ord(S1)\n");
      PX.CHECK(Concatenation(name, ": icosahedral order obstruction applies for m = ", String(tg.m)), true);
      continue;
    fi;
    if (tg.m = 4 or q = 4) and not Order(S1) in PX.OrdersOO then
      Print("\n-- target ord(X) = ", tg.m, " (k = ", tg.k, "): EXCLUDED a priori: the vertex-figure group would be S4, ",
            "forcing Gamma <= +-[O x O] (order 1152), which has no element of order ", Order(S1), " = ord(S1)\n");
      PX.CHECK(Concatenation(name, ": octahedral order obstruction applies for m = ", String(tg.m)), true);
      continue;
    fi;
    ## target trace: 2 + 2cos(2 pi k/m), plus 1 for the 5-dimensional simplex coordinates
    c := 2 + E(tg.m)^tg.k + E(tg.m)^(-tg.k);
    if T.hyper <> fail then c := c + 1; fi;
    poly := tau - c*d1*d2*dh;
    Print("\n-- target ord(X) = ", tg.m, " (k = ", tg.k, "): tr(X) = ", c,
          " ~ ", PX.Float(c), ";  polynomial of degree ", DegreeOfLaurentPolynomial(poly), "\n");
    if IsZero(poly) then
      Print("   the equation holds identically: every base vertex gives ord(X) = ", tg.m, " (unexpected)\n");
      continue;
    fi;
    sol := PX.RealRootsExact(poly, t);
    Print("   factors over Q(sqrt5): ", List(sol.factors, f -> DegreeOfLaurentPolynomial(f)),
          "; exact real roots found: ", Length(sol.roots), "\n");
    for r in sol.unresolved do
      Print("   factor of degree ", r.degree, ": ", r.factor);
      Print("   [", r.reason);
      if IsBound(r.real_roots) then Print("; real roots: ", r.real_roots); fi;
      Print("]\n");
      ## try to settle a quadratic factor with real roots but non-cyclotomic
      ## square root of the discriminant
      if IsBound(r.real_roots) and r.real_roots > 0 and r.degree = 2 and IsBound(r.discriminant) then
        ab := PX.IsAbelianQuadExtOfQ5(r.discriminant);
        Print("      K(sqrt D)/Q abelian (Kronecker-Weber test on the norm of the discriminant): ", ab, "\n");
        if ab = false then
          killed := false;
          for g in [S1, S1^2, S2, S1*S2, S1^3] do
            cf := PX.RationalModFactor(Trace(g*S2^-1*N), d1*d2*dh, r.factor, t);
            if cf <> fail then
              Print("      tr(", "g X", ") = ", cf[1], " + (", cf[2], ") t");
              if not IsZero(cf[2]) then
                Print("   -> not in any cyclotomic field, so Gamma is infinite: NO POLYTOPE\n");
                killed := true; break;
              else
                Print("   (lies in Q(sqrt5); no information)\n");
              fi;
            fi;
          od;
          if killed then
            PX.CHECK(Concatenation(name, ": the non-cyclotomic quadratic factor for m = ", String(tg.m),
                     " is killed by the Kronecker-Weber trace obstruction"), true);
            continue;
          fi;
        fi;
      fi;
      Add(res.unresolved, rec(target := tg, factor := r));
      if IsBound(r.real_roots) and r.real_roots > 0 and not IsBound(r.discriminant) then
        Add(res.hard, rec(target := tg, factor := r));
      elif IsBound(r.real_roots) and r.real_roots > 0 then
        Add(res.hard, rec(target := tg, factor := r));
      fi;
    od;
    for root in sol.roots do
      w := root*T.v0 + T.v3;
      if w = 0*w then Print("   root t = ", root, " gives w = 0 (skipped)\n"); continue; fi;
      alpha := PX.AlphaOf(T, root, 1);
      Print("   root t = ", root, " ~ ", PX.Float(root), "  ->  alpha = ", alpha.alpha);
      if alpha.alpha <> infinity and alpha.exact then Print(" ~ ", PX.Float(alpha.alpha)); fi;
      Print("\n");
      Add(res.roots, rec(target := tg, t := root, alpha := alpha, w := w));
    od;
  od;
  ## t = infinity, i.e. w = v0 (alpha = 0), is not covered by the polynomial in t
  Add(res.roots, rec(target := rec(m := fail, k := fail), t := infinity, alpha := rec(alpha := 0, exact := true), w := T.v0));
  ## verify every root completely
  Print("\n-- verification of every candidate base vertex --\n");
  for r in res.roots do
    cnt := cnt + 1;
    cid := Concatenation("L3-", name, "-", String(cnt));
    u := PX.UniqueThirdGenerator(T, S1, S2, r.w);
    if not u.exists then
      Print(cid, ": t = ", r.t, ", alpha = ", r.alpha.alpha, ": ", u.reason, "\n");
      continue;
    fi;
    Print(cid, ": t = ", r.t, ", alpha = ", r.alpha.alpha, ", ord(X) = ", u.order,
          ", conditions of E1 all hold: ", u.all, ", det X = ", u.det_X, "\n");
    PX.CHECK(Concatenation(cid, ": the unique X satisfies all conditions of Prop. E1"), u.all);
    if r.target.m <> fail then
      PX.CHECKEQ(Concatenation(cid, ": ord(X) equals the target"), u.order, r.target.m);
    fi;
    if u.order < 3 then
      Print("   ord(X) = ", u.order, " < 3: degenerate (p3 < 3), rejected\n");
      classification := "PROVED-OBSTRUCTION-IN-PARENT"; note := Concatenation("ord(X) = ", String(u.order), " < 3");
      AppendTo(PX.AlphaTSV, JoinStringsWithSeparator(List([cid, name, String(r.target.m), String(r.target.k),
        String(r.t), String(r.alpha.alpha), "-", u.order, "-", "-", "-", "-", "-", "-", "-", "-", "-",
        classification, note], String), "\t"), "\n");
      continue;
    fi;
    vfg := PX.VertexFigureGroupType(S2, u.X, r.w);
    Print("   vertex-figure group <S2,X>: order ", vfg.size, ", ", vfg.structure,
          ", polyhedral (A4/S4/A5): ", vfg.polyhedral, "\n");
    PX.CHECK(Concatenation(cid, ": the vertex-figure group is A4, S4 or A5 (Prop. E2)"), vfg.polyhedral);
    ## safe finiteness test before any group computation
    ## cap 8000 > 7200: by Prop. E4 a finite Gamma is conjugate into one of the
    ## groups (2X x 2Y)/{+-1} with X,Y in {T,O,I}, the largest of which is
    ## [3,3,5]^+ of order 7200; so an orbit exceeding 7200 proves Gamma infinite,
    ## hence non-discrete, hence not the group of a skeletal polytope.
    sg := PX.SafeGamma([S1, S2, u.X], r.w, 8000, PX.EffDim(T));
    if sg.finite <> true then
      Print("   the vertex orbit exceeds the cap (8000 > 7200) or fails to span (orbit size ", sg.orbit_size,
            ", capped: ", IsBound(sg.capped) and sg.capped = true, ", spans: ", IsBound(sg.spans) and sg.spans = true,
            "): recorded as UNRESOLVED\n");
      AppendTo(PX.AlphaTSV, JoinStringsWithSeparator(List([cid, name, String(r.target.m), String(r.target.k),
        String(r.t), String(r.alpha.alpha), "-", u.order, String(vfg.size), true, "-", "-", "-", "-", "-", "-", "-",
        "PROVED-OBSTRUCTION-IN-PARENT", Concatenation("vertex orbit exceeds 7200 (reached ", String(sg.orbit_size),
        "), so Gamma is infinite by Prop. E4 and not the group of a skeletal polytope")], String), "\t"), "\n");
      continue;
    fi;
    Print("   |Gamma| = ", sg.order, " (faithful action on ", sg.orbit_size, " vertices spanning E^", PX.EffDim(T), ")\n");
    ps := PX.PermSetup(Group([S1, S2, u.X]));
    s := List([S1, S2, u.X], ps.im);
    ip := PX.IntersectionData(ps.P, s);
    Print("   |Gamma| = ", Size(ps.P), ", intersection condition ", [ip.i12_trivial, ip.i23_trivial, ip.I_equals_S2],
          " (defect ", ip.defect, ")\n");
    if not ip.holds then
      classification := "PROVED-OBSTRUCTION-IN-PARENT";
      note := Concatenation("intersection condition fails, defect ", String(ip.defect));
      Print("   -> ", note, "\n");
      AppendTo(PX.AlphaTSV, JoinStringsWithSeparator(List([cid, name, String(r.target.m), String(r.target.k),
        String(r.t), String(r.alpha.alpha), "-", u.order, String(vfg.size), true, false, ip.defect,
        "-", "-", "-", "-", "-", classification, note], String), "\t"), "\n");
      continue;
    fi;
    full := PX.FullVerify(T, [S1, S2, u.X], r.w, Concatenation("LEVEL 3 ", cid, ": T = ", name,
              ", alpha = ", String(r.alpha.alpha), ", ord(X) = ", String(u.order)));
    if full.skeletal_polytope then
      classification := "PROVED-CONSTRUCTION"; note := "faithful chiral skeletal 4-polytope";
    else
      classification := "PROVED-OBSTRUCTION-IN-PARENT"; note := "abstract polytope exists but the realisation is not faithful";
    fi;
    if full.skeletal_polytope then
      AppendTo(PX.AlphaSaved, "Add(PX.Saved, rec(case := \"", cid, "\", T := \"", name,
               "\", parent := \"O(4) (Level 3)\", alpha := ", r.alpha.alpha, ", ab := ", [r.t, 1], ", S1 := ", S1,
               ", S2 := ", S2, ", X := ", u.X, ", w := ", r.w, ", skeletal := true, directly_regular := ",
               full.mirror.directly_regular, "));\n");
    fi;
    Add(PX.AllRoots, rec(case := cid, T := name, alpha := r.alpha.alpha, t := r.t, X := u.X, w := r.w,
                         order := u.order, vfg := vfg.size, fvector := full.fvector_abstract,
                         skeletal := full.skeletal_polytope, chiral := full.geometrically_chiral,
                         directly_regular := full.mirror.directly_regular, classification := classification));
    AppendTo(PX.AlphaTSV, JoinStringsWithSeparator(List([cid, name, String(r.target.m), String(r.target.k),
      String(r.t), String(r.alpha.alpha), "-", u.order, String(vfg.size), full.strings.holds, true, 1,
      String(full.fvector_abstract), full.mirror.directly_regular, full.faithful, full.skeletal_polytope,
      full.geometrically_chiral, classification, note], String), "\t"), "\n");
  od;
  PX.AlphaResultsComplete.(name) := res;
  return res;
end;

## the ten rows (the T* endpoint of each row is the point alpha = 1 = t = 0 of
## the same circle, so the analysis of the row covers both endpoints)
for row in [1..10] do
  PX.AnalyseRow(PX.Order[2*row-1]);
od;

#############################################################################
##  Summary
#############################################################################
Print("\n\n############################################################\n");
Print("## Level 3 summary: every base vertex on every PETCOX circle whose\n");
Print("## unique third generator has order 3, 4 or 5\n");
Print("############################################################\n");
for row in [1..10] do
  name := PX.Order[2*row-1];
  res := PX.AlphaResultsComplete.(name);
  Print(name, ": candidate base vertices ", Length(res.roots), " (alphas ",
        List(res.roots, r -> r.alpha.alpha), "), unresolved factors ", Length(res.unresolved), "\n");
od;
Print("\nSurviving faithful skeletal 4-polytopes:\n");
for r in PX.AllRoots do
  if r.skeletal then
    Print("  ", r.case, ": T = ", r.T, ", alpha = ", r.alpha, ", ord(X) = ", r.order,
          ", f-vector ", r.fvector, ", geometrically chiral ", r.chiral,
          ", directly regular ", r.directly_regular, "\n");
  fi;
od;
Print("\nUnresolved factors with real roots (these would need an algebraic extension):\n");
nhard := 0;
for row in [1..10] do
  name := PX.Order[2*row-1];
  for h in PX.AlphaResultsComplete.(name).hard do
    Print("  ", name, ": target ord(X) = ", h.target.m, " (k = ", h.target.k, "), factor of degree ", h.factor.degree,
          " with ", h.factor.real_roots, " real roots: ", h.factor.factor, "\n");
    nhard := nhard + 1;
  od;
od;
if nhard = 0 then Print("  none: every polynomial factor was either solved exactly or proved to have no real roots.\n"); fi;
PX.CHECKEQ("number of polynomial factors with real roots that could not be solved exactly", nhard, 0);

PX.Summary("alpha-complete.g");
if PX.nfail > 0 then QuitGap(1); fi;
Print("Done: alpha-complete.g\n");
