#############################################################################
##
##  canonical.g  --  Level 1: the canonical extension
##      S1 = R0 R1 R3 R2,  S2 = R2 R1,  S3 = R3 R2,   base vertex v0 (alpha = 0)
##  for each of the 16 regular 4-polytopes T (20 records: the four self-dual
##  polytopes appear twice, once per endpoint alpha = 0 / alpha = 1 of the
##  PETCOX family; H_1(T) = H_0(T^*)).
##
##  Run from gap/:   gap -q -A --quitonbreak canonical.g < /dev/null
##  Writes ../logs/canonical-rows.tsv (one row per record).
##
#############################################################################

if not IsBound(PX) then Read("lib.g"); fi;
if not IsBound(PX.T) or Length(RecNames(PX.T)) = 0 then Read("polytopes.g"); PX.BuildAll(); PX.SetupRows(); fi;

PX.CanonicalResults := rec();
PX.TSVFile := "../logs/canonical-rows.tsv";
PrintTo(PX.TSVFile, JoinStringsWithSeparator([
  "case_id","T","alpha","facet","facet_group_order","gamma_order","S3","orders","string_relations","intersection_condition","ip_defect",
  "fvector","directly_regular","faithful","skeletal_polytope","geometrically_chiral","combinatorially_chiral","classification","note"], "\t"), "\n");

PX.Known := rec( ("{4,3,3}") := "KNOWN-CONSTRUCTION: Roli's cube (Bracho-Hubard-Pellicer 2014), type {8,3,3}",
                 ("{5/2,3,5}") := "KNOWN-CONSTRUCTION: thesis {12/(1,5),3,5}, facets H_1({5,3,5/2}) = H_0({5/2,3,5})",
                 ("{5,3,5/2}") := "KNOWN-CONSTRUCTION: thesis {12/(1,5),3,5/2}, facets H_0({5,3,5/2})" );

for name in PX.Order do
  T := PX.T.(name);
  row := PX.RowOf.(name);
  side := 1; if PX.Order[2*row] = name then side := 2; fi;   # side 2 = the dual endpoint (alpha = 1 of the row's T)
  tab := PX.Table[row];
  tw := PX.TableTwist[row];
  label := Concatenation("CANONICAL ", name, "  (facet H_0(", name, ")",
             " = H_1(", PX.DualName.(name), "); PETCOX row ", String(row), ", endpoint alpha=", String(side-1), " of ", tab.T, ")");
  Print("\n\n##########################################################################\n", label, "\n");
  S := PX.CanonicalTriple(T);
  ps := PX.PermSetup(T.W);
  s := List(S, ps.im);
  P := ps.P;
  Gam := Subgroup(P, s); G := Subgroup(P, s{[1,2]}); VF := Subgroup(P, s{[2,3]});
  ## Gamma = W^+ (the rotation subgroup): index 2 and generated by even words
  Wplus := Subgroup(P, [ps.im(T.R[1]*T.R[2]), ps.im(T.R[2]*T.R[3]), ps.im(T.R[3]*T.R[4])]);
  PX.CHECK(Concatenation(name, ": Gamma = <S1,S2,S3> equals the rotation subgroup W^+ of W"), Gam = Wplus);
  PX.CHECKEQ(Concatenation(name, ": |Gamma|"), Size(Gam), Size(P)/2);
  PX.CHECK(Concatenation(name, ": S1 S3^-1 = R0 R1"), S[1]*S[3]^-1 = T.R[1]*T.R[2]);
  st := PX.StringRelations(s);
  PX.CHECK(Concatenation(name, ": (S1S2)^2=(S2S3)^2=(S1S2S3)^2=1"), st.holds);
  ## facet data against the PETCOX table
  PX.CHECKEQ(Concatenation(name, ": |<S1,S2>| = #(G) of the table"), Size(G), tab.G);
  PX.CHECKEQ(Concatenation(name, ": [Gamma^+(T) : G] = index column of the table"), Size(Gam)/Size(G), tab.index);
  twist := PX.TwistType(S[1], T.hyper);
  PX.CHECKEQ(Concatenation(name, ": order p of S1"), twist.p, tw[1]);
  PX.CHECK(Concatenation(name, ": twist pair (p1,p2) of S1 equals the table's ", String([tw[2],tw[3]])), [tw[2],tw[3]] in twist.pairs);
  PX.CHECKEQ(Concatenation(name, ": q = order of S2"), Order(s[2]), tw[4]);
  ## intersection condition and the collapse column
  ip := PX.IntersectionData(P, s);
  Print("intersection condition: ", [ip.i12_trivial, ip.i23_trivial, ip.I_equals_S2], "  defect |<S1,S2> cap <S2,S3> : <S2>| = ", ip.defect, "\n");
  ## geometric collapse multiplicity at w = v0: |Stab_G(v0)| / q
  Gm := Group(S{[1,2]});
  stabG := Stabilizer(Gm, T.v0, OnPoints);
  mult := Size(stabG)/Order(S[2]);
  Print("vertex-collapse multiplicity of the facet at alpha=0: |Stab_G(v0)|/q = ", mult, "\n");
  PX.CHECKEQ(Concatenation(name, ": collapse multiplicity equals the intersection defect"), mult, ip.defect);
  PX.CHECKEQ(Concatenation(name, ": collapse multiplicity equals the table entry"), mult, tab.collapse[side]);
  PX.CHECK(Concatenation(name, ": Stab_G(v0) = G cap <S2,S3>"), ps.im(stabG) = ip.I or Image(ps.iso, stabG) = ip.I);
  res := rec(name := name, row := row, side := side, S := S, s := s, P := P, ip := ip, twist := twist, strings := st,
             G_order := Size(G), gamma_order := Size(Gam), mult := mult);
  if ip.holds then
    res.full := PX.FullVerify(T, S, T.v0, label);
    fv := res.full;
    PX.CHECK(Concatenation(name, ": faithful Wythoff realisation"), fv.faithful);
    PX.CHECK(Concatenation(name, ": skeletal 4-polytope conditions"), fv.skeletal_polytope);
    PX.CHECK(Concatenation(name, ": abstract f-vector = geometric f-vector"), fv.fvector_abstract = fv.fvector_geometric);
    PX.CHECK(Concatenation(name, ": half-turn candidate exists and is an involutory isometry inverting S1"),
             fv.halfturn.exists and fv.halfturn.orthogonal and fv.halfturn.involution and fv.halfturn.inverts_S1 and fv.halfturn.maps_w_to_wS1inv);
    PX.CHECK(Concatenation(name, ": geometrically chiral"), fv.geometrically_chiral);
    PX.CHECK(Concatenation(name, ": facet H_0 is a geometrically chiral polyhedron"), fv.facet.polyhedron and fv.facet.geometrically_regular = false);
    PX.CHECK(Concatenation(name, ": facet is combinatorially regular (rank-3 mirror automorphism exists)"), fv.facet_abstract.mirror.directly_regular);
    if IsBound(PX.Known.(name)) then
      classification := "KNOWN-CONSTRUCTION"; note := PX.Known.(name);
    else
      classification := "PROVED-CONSTRUCTION"; note := "new candidate from the canonical extension; see RESULT.md for novelty status";
    fi;
    if name in ["{3,3,3}*","{3,4,3}*","{5,5/2,5}*","{5/2,5,5/2}*"] then classification := "DUPLICATE"; note := "self-dual T: alpha=1 endpoint congruent to alpha=0 endpoint"; fi;
    fields := [ Concatenation("C", String(row), String(side)), name, "0", Concatenation("H_0(", name, ")"), Size(G), Size(Gam), "R3R2 (canonical)",
                String(List(s, Order)), st.holds, true, ip.defect, String(fv.fvector_abstract), fv.mirror.directly_regular,
                fv.faithful, fv.skeletal_polytope, fv.geometrically_chiral, not fv.mirror.directly_regular, classification, note ];
  else
    classification := "PROVED-OBSTRUCTION-CANONICAL";
    note := Concatenation("intersection condition fails: |<S1,S2> cap <S2,S3> : <S2>| = ", String(ip.defect),
              " = vertex-collapse multiplicity of H_0(", name, ") (table: ", String(tab.collapse[side]), ")");
    if name in ["{3,3,3}*","{3,4,3}*","{5,5/2,5}*","{5/2,5,5/2}*"] then note := Concatenation(note, "; self-dual T, same as the alpha=0 endpoint"); fi;
    fields := [ Concatenation("C", String(row), String(side)), name, "0", Concatenation("H_0(", name, ")"), Size(G), Size(Gam), "R3R2 (canonical)",
                String(List(s, Order)), st.holds, false, ip.defect, "-", "-", "-", "-", "-", "-", classification, note ];
    Print("-> ", classification, ": ", note, "\n");
  fi;
  res.classification := classification; res.note := note;
  PX.CanonicalResults.(name) := res;
  AppendTo(PX.TSVFile, JoinStringsWithSeparator(List(fields, String), "\t"), "\n");
od;

#############################################################################
##  Compare the surviving canonical candidates with each other
##  (abstract isomorphism, enantiomorphism, duality; geometric invariants)
#############################################################################
Print("\n\n########## Comparison of the surviving canonical candidates ##########\n");
surv := Filtered(PX.Order, n -> PX.CanonicalResults.(n).ip.holds);
Print("survivors: ", surv, "\n");
PX.GramInvariant := function(V)   # sorted multiset of normalised inner products (congruence invariant of the vertex set)
  local n2, i, j, l;
  n2 := V[1]*V[1];
  l := [];
  for i in [1..Length(V)] do for j in [i+1..Length(V)] do Add(l, (V[i]*V[j])/n2); od; od;
  return Collected(l);
end;
PX.EdgeAngle := function(Wy)  # normalised inner product along the base edge
  local e; e := Wy.e; return (Wy.V[e[1]]*Wy.V[e[2]])/(Wy.V[e[1]]*Wy.V[e[1]]);
end;
for i in [1..Length(surv)] do for j in [i+1..Length(surv)] do
  a := PX.CanonicalResults.(surv[i]); b := PX.CanonicalResults.(surv[j]);
  cmp := PX.CompareTriples(Subgroup(a.P, a.s), a.s, Subgroup(b.P, b.s), b.s);
  Print(surv[i], " vs ", surv[j], ": abstractly isomorphic (same orientation / mirror): ", cmp.isomorphic_same_orientation, " / ", cmp.isomorphic_mirror,
        "; dual (same / mirror): ", cmp.dual_same, " / ", cmp.dual_mirror,
        "; edge inner product ", PX.EdgeAngle(a.full.Wy), " vs ", PX.EdgeAngle(b.full.Wy),
        "; same vertex Gram multiset: ", PX.GramInvariant(a.full.Wy.V) = PX.GramInvariant(b.full.Wy.V), "\n");
od; od;

PX.Summary("canonical.g");
if PX.nfail > 0 then QuitGap(1); fi;
Print("Done: canonical.g\n");
