#############################################################################
##
##  parent-search.g  --  Level 2: exhaustive search for third generators X
##  inside finite parent groups, keeping the PETCOX facet generators S1, S2.
##
##  For a polytope record T with facet generators S1 = R0R1R3R2, S2 = R2R1,
##  and a finite matrix group PARENT containing S1, S2, every X in PARENT is
##  tested:
##    (a) (S2 X)^2 = 1 and (S1 S2 X)^2 = 1                 (rotation relations);
##    (b) the fixed space of X meets the plane span(v0,v3) = Fix(S2) in a
##        line (then the base vertex w and its PETCOX parameter alpha are
##        determined exactly), and X fixes the base edge {w, w S1^-1};
##    (c) ord(X) >= 3 (ord(X) = 2 gives p3 = 2: degenerate);
##    (d) <S2> cap <X> = 1 and <S1,S2> cap <S2,X> = <S2> (exact subgroup
##        equality in a permutation image of PARENT);
##    (e) full verification (lib.g PX.FullVerify): faithful Wythoff
##        realisation at w, skeletal polytope conditions, chirality.
##  Every rejected X is counted with the first failing condition; every
##  survivor is verified and compared with the canonical candidates.
##
##  Parents used:
##    * W(T) for all 16 T (the symmetry group of T; contains G = <S1,S2>);
##    * extended reflection-group parents where W(T) is not maximal:
##        {3,3,3}      -> [3,3,5] (an A4 reflection subgroup of H4),
##        {4,3,3}, {3,3,4}, {3,4,3} -> [3,4,3] and [[3,4,3]] (order 2304);
##    * N_{O(4)}(G), the full normaliser of the facet group in O(4), when it
##      is finite (computed from Aut(G) by solving X S_i = phi(S_i) X); this
##      contains every finite subgroup of O(4) in which G is normal, e.g.
##      +-[I x O] for the facet groups of order 1440.
##
#############################################################################

if not IsBound(PX) then Read("lib.g"); fi;
if not IsBound(PX.T) or Length(RecNames(PX.T)) = 0 then Read("polytopes.g"); PX.BuildAll(); PX.SetupRows(); fi;

PX.ParentTSV := "../logs/parent-rows.tsv";
PrintTo(PX.ParentTSV, JoinStringsWithSeparator([
  "case_id","T","parent","parent_order","alpha","ab_coordinates","X_order","X_description","facet","orders","string_relations",
  "intersection_condition","ip_defect","fvector","directly_regular","faithful","skeletal_polytope","geometrically_chiral",
  "combinatorially_chiral","classification","note"], "\t"), "\n");
PX.ParentSurvivors := [];
PX.ParentStats := rec();
PX.SavedFile := "../logs/parent-survivors.g";
PrintTo(PX.SavedFile, "# machine-generated by parent-search.g: every candidate triple that passed the intersection condition\n",
        "if not IsBound(PX.Saved) then PX.Saved := []; fi;\n");

## describe X as a word if it lies in W(T) (in the R_i), else by its order/type
PX.DescribeX := function(T, X, S)
  local ps, im, epi, w;
  if X in T.W then
    ps := PX.PermSetup(T.W);
    epi := EpimorphismFromFreeGroup(ps.P : names := ["R0","R1","R2","R3"]);
    w := PreImagesRepresentative(epi, ps.im(X));
    return Concatenation("word ", String(w));
  fi;
  return Concatenation("outside W(T); order ", String(Order(X)), ", det ", String(DeterminantMat(X)));
end;

## The search.  Returns the list of surviving records.
PX.ParentSearch := function(T, PARENT, parentname, caseprefix)
  local S, S1, S2, I, els, X, stats, L, ab, w, cnt, rel, cand, ps, s, ip, o, res, surv, k, fv, alpha, fields,
        classification, note, wS1inv, eq, facetOK, F3, labelX, seen, key, dup, c, sym;
  S := PX.CanonicalTriple(T); S1 := S[1]; S2 := S[2];
  I := IdentityMat(T.dim);
  Print("\n\n################ PARENT SEARCH: T = ", T.name, ", parent = ", parentname, " (order ", Size(PARENT), ") ################\n");
  if not (S1 in PARENT and S2 in PARENT) then Error("parent does not contain the facet generators"); fi;
  els := AsList(PARENT);
  stats := rec(total := Length(els), relations := 0, fixedline := 0, order_ge3 := 0, edge := 0, ip := 0, survivors := 0,
               rejected_relations := 0, rejected_nofixedpoint := 0, rejected_fixesplane := 0, rejected_order2 := 0,
               rejected_edge := 0, rejected_ip := 0, rejected_realisation := 0);
  cand := [];
  for X in els do
    if not ((S2*X)^2 = I and (S1*S2*X)^2 = I) then stats.rejected_relations := stats.rejected_relations + 1; continue; fi;
    stats.relations := stats.relations + 1;
    L := PX.FixedLocusInPlane(T, X);
    if Length(L) = 0 then stats.rejected_nofixedpoint := stats.rejected_nofixedpoint + 1; continue; fi;
    if Length(L) = 2 then stats.rejected_fixesplane := stats.rejected_fixesplane + 1; continue; fi;   # X in <R1,R2>: fixes the whole circle
    stats.fixedline := stats.fixedline + 1;
    if Order(X) < 3 then stats.rejected_order2 := stats.rejected_order2 + 1; continue; fi;
    stats.order_ge3 := stats.order_ge3 + 1;
    ab := L[1]; w := ab[1]*T.v0 + ab[2]*T.v3;
    wS1inv := w*S1^-1;
    if not (wS1inv*X = wS1inv) then stats.rejected_edge := stats.rejected_edge + 1; continue; fi;
    stats.edge := stats.edge + 1;
    Add(cand, rec(X := X, ab := ab, w := w));
  od;
  Print("elements: ", stats.total, "; satisfying (S2X)^2=(S1S2X)^2=1: ", stats.relations,
        "; of these with a fixed LINE in the plane: ", stats.fixedline, " (no fixed point: ", stats.rejected_nofixedpoint,
        ", fixing the whole plane: ", stats.rejected_fixesplane, "); order >= 3: ", stats.order_ge3,
        " (order 2 rejected: ", stats.rejected_order2, "); fixing the base edge: ", stats.edge, "\n");
  ## group-theoretic conditions in a permutation image of the group generated by S1,S2 and all candidates
  ps := PX.PermSetup(PARENT);
  s := List(S{[1,2]}, ps.im);
  surv := [];
  seen := [];
  for c in cand do
    X := c.X;
    alpha := PX.AlphaOf(T, c.ab[1], c.ab[2]);
    labelX := Concatenation("X of order ", String(Order(X)), ", alpha = ", String(alpha.alpha), " (a:b = ", String(c.ab), ")");
    ip := PX.IntersectionData(ps.P, [s[1], s[2], ps.im(X)]);
    if not ip.holds then
      stats.rejected_ip := stats.rejected_ip + 1;
      Print("  reject ", labelX, ": intersection condition fails (", [ip.i12_trivial, ip.i23_trivial, ip.I_equals_S2], ", defect ", ip.defect, ")\n");
      continue;
    fi;
    stats.ip := stats.ip + 1;
    ## conjugacy deduplication: X and X' equivalent if X' = g X g^-1 with g in the centraliser of <S1,S2> in PARENT
    key := fail;
    for k in [1..Length(seen)] do
      if RepresentativeAction(Centralizer(ps.P, Subgroup(ps.P, s)), seen[k].xperm, ps.im(X)) <> fail then key := k; break; fi;
    od;
    if key <> fail then
      Print("  ", labelX, ": conjugate (under the centraliser of the facet group) to candidate ", key, " -> DUPLICATE\n");
      fields := [ Concatenation(caseprefix, "-", String(Length(seen)), "dup"), T.name, parentname, Size(PARENT), String(alpha.alpha), String(c.ab), Order(X),
                  PX.DescribeX(T, X, S), Concatenation("H_alpha(", T.name, ")"), String(List([S1,S2,X], Order)), true, true, 1, "-", "-", "-", "-", "-", "-",
                  "DUPLICATE", Concatenation("conjugate to candidate ", String(key), " of this search") ];
      AppendTo(PX.ParentTSV, JoinStringsWithSeparator(List(fields, String), "\t"), "\n");
      continue;
    fi;
    Add(seen, rec(xperm := ps.im(X)));
    ## full verification at w
    res := PX.FullVerify(T, [S1, S2, X], c.w, Concatenation("PARENT ", parentname, ", T = ", T.name, ", ", labelX));
    res.X := X; res.ab := c.ab; res.alpha := alpha; res.parent := parentname; res.T := T.name;
    Print("alpha = ", alpha.alpha, " (exact: ", alpha.exact, "); X = ", PX.DescribeX(T, X, S), "\n");
    if res.abstract_polytope and res.skeletal_polytope then
      stats.survivors := stats.survivors + 1;
      classification := "PROVED-CONSTRUCTION"; note := "see comparison with the canonical candidates";
      if X = S[3] then note := "this is the canonical S3 = R3 R2 (alpha = 0)"; fi;
    else
      stats.rejected_realisation := stats.rejected_realisation + 1;
      classification := "PROVED-OBSTRUCTION-IN-PARENT";
      note := "abstract polytope exists but the Wythoff realisation at w is not a faithful skeletal 4-polytope";
      if not res.abstract_polytope then note := "no abstract polytope"; fi;
    fi;
    Add(surv, res);
    AppendTo(PX.SavedFile, "Add(PX.Saved, rec(case := \"", Concatenation(caseprefix, "-", String(Length(seen))), "\", T := \"", T.name,
             "\", parent := \"", parentname, "\", alpha := ", alpha.alpha, ", ab := ", c.ab, ", S1 := ", S1, ", S2 := ", S2, ", X := ", X,
             ", w := ", c.w, ", skeletal := ", res.skeletal_polytope, ", directly_regular := ", res.mirror.directly_regular, "));\n");
    fields := [ Concatenation(caseprefix, "-", String(Length(seen))), T.name, parentname, Size(PARENT), String(alpha.alpha), String(c.ab), Order(X),
                PX.DescribeX(T, X, S), Concatenation("H_alpha(", T.name, ")"), String(res.orders), res.strings.holds, true, 1,
                String(res.fvector_abstract), res.mirror.directly_regular, res.faithful, res.skeletal_polytope, res.geometrically_chiral,
                not res.mirror.directly_regular, classification, note ];
    AppendTo(PX.ParentTSV, JoinStringsWithSeparator(List(fields, String), "\t"), "\n");
  od;
  Print("STATS ", T.name, " in ", parentname, ": ", stats, "\n");
  PX.ParentStats.(Concatenation(T.name, " in ", parentname)) := stats;
  return surv;
end;

#############################################################################
##  N_{O(4)}(G): the normaliser of the facet group in O(4) via Aut(G)
#############################################################################
PX.NormaliserInO := function(T)
  local S, S1, S2, Gm, ps, Gp, A, Inn, reps, phi, g1, g2, d, rows, sol, i, j, Ek, X0, c, sq, R, r, gens, N, idsol;
  S := PX.CanonicalTriple(T); S1 := S[1]; S2 := S[2];
  d := T.dim;
  Gm := Group([S1,S2]);
  ps := PX.PermSetup(Gm);
  Gp := ps.P;
  A := AutomorphismGroup(Gp);
  Inn := InnerAutomorphismsAutomorphismGroup(A);
  ## Conjugation by an element of N_{O(4)}(G) induces an automorphism of G; the kernel of N -> Aut(G) is the
  ## centraliser C_{O(4)}(G), which is {+-I} when the commutant of G is the scalars (solution space of the identity
  ## automorphism 1-dimensional).  Inner automorphisms are induced by G itself, so N is generated by G, -I and one
  ## solution X_phi for each coset of Inn(G) in Aut(G) whose automorphisms are induced by an orthogonal matrix.
  reps := List(RightTransversal(A, Inn), x -> x);
  r := rec(aut_order := Size(A), inner := Size(Inn), out := Size(A)/Size(Inn), dims := [], failed_sqrt := 0, realised := 0);
  gens := Concatenation(ShallowCopy([S1, S2]), [-IdentityMat(d)]);
  ## solve X S_i = phi(S_i) X (linear in X); for the simplex also X fixes the all-ones vector (handled below)
  for phi in reps do
    g1 := PreImagesRepresentative(ps.iso, Image(phi, ps.im(S1)));
    g2 := PreImagesRepresentative(ps.iso, Image(phi, ps.im(S2)));
    rows := [];
    for i in [1..d] do for j in [1..d] do
      Ek := NullMat(d, d); Ek[i][j] := 1;
      if T.hyper = fail then
        Add(rows, Concatenation(Concatenation(Ek*S1 - g1*Ek), Concatenation(Ek*S2 - g2*Ek)));
      else
        Add(rows, Concatenation(Concatenation(Ek*S1 - g1*Ek), Concatenation(Ek*S2 - g2*Ek), T.hyper*Ek));
      fi;
    od; od;
    sol := NullspaceMat(rows);
    Add(r.dims, Length(sol));
    if Length(sol) = 1 then
      X0 := List([1..d], i -> sol[1]{[(i-1)*d+1..i*d]});
      R := PX.OrthogonaliseIntertwiner(X0, T.hyper);
      if R = fail then r.failed_sqrt := r.failed_sqrt + 1;
      else Add(gens, R); r.realised := r.realised + 1; fi;
    fi;
  od;
  ## the identity automorphism is among the representatives only if reps contains it; compute the commutant dimension directly
  rows := [];
  for i in [1..d] do for j in [1..d] do
    Ek := NullMat(d, d); Ek[i][j] := 1;
    if T.hyper = fail then
      Add(rows, Concatenation(Concatenation(Ek*S1 - S1*Ek), Concatenation(Ek*S2 - S2*Ek)));
    else
      Add(rows, Concatenation(Concatenation(Ek*S1 - S1*Ek), Concatenation(Ek*S2 - S2*Ek), T.hyper*Ek));
    fi;
  od; od;
  r.commutant_dim := Length(NullspaceMat(rows));
  r.finite := (r.commutant_dim = 1);
  ## |N| = 2 |Inn(G)| r, because N -> Aut(G) has kernel C_{O(d)}(G) = {+-I}
  ## (the commutant of G in the matrix algebra is R.I) and image the group of
  ## automorphisms induced, which contains Inn(G) and is generated by Inn(G)
  ## together with the realised outer classes.
  r.inn := Size(Gp)/Size(Centre(Gp));
  r.order_formula := 2*r.inn*r.realised;
  r.gens := gens;
  r.elements := fail;
  if r.finite and r.order_formula <= 12000 then
    N := Group(gens);
    r.N := N;
    r.elements := AsList(N);
    r.order := Length(r.elements);
    r.contains_W := ForAll(T.R, x -> x in r.elements);
    r.rotations := Filtered(r.elements, x -> DeterminantMat(x) = 1);
    r.closed := (r.order = r.order_formula);
  else
    r.order := r.order_formula;
    r.contains_W := fail; r.rotations := fail; r.closed := fail;
  fi;
  return r;
end;

#############################################################################
##  The rho_1-type half-turn of the facet family, obtained by an exact linear
##  solve instead of a group enumeration: R inverts S1 and S2 by conjugation
##  iff R S1 = S1^-1 R and R S2 = S2^-1 R, which is linear in R.  When the
##  solution space is 1-dimensional the two half-turns are +-R, and the point
##  of the PETCOX circle they fix is the geometrically regular member of the
##  family (PETCOX Lemma 3 and Theorem 9).
#############################################################################
PX.Rho1Intertwiner := function(T)
  local S, S1, S2, d, rows, i, j, Ek, sol, X0, c, sq, R, r;
  S := PX.CanonicalTriple(T); S1 := S[1]; S2 := S[2];
  d := T.dim;
  rows := [];
  for i in [1..d] do for j in [1..d] do
    Ek := NullMat(d, d); Ek[i][j] := 1;
    if T.hyper = fail then
      Add(rows, Concatenation(Concatenation(Ek*S1 - S1^-1*Ek), Concatenation(Ek*S2 - S2^-1*Ek)));
    else
      Add(rows, Concatenation(Concatenation(Ek*S1 - S1^-1*Ek), Concatenation(Ek*S2 - S2^-1*Ek), T.hyper*Ek));
    fi;
  od; od;
  sol := NullspaceMat(rows);
  r := rec(dim := Length(sol));
  if Length(sol) <> 1 then return r; fi;
  X0 := List([1..d], i -> sol[1]{[(i-1)*d+1..i*d]});
  R := PX.OrthogonaliseIntertwiner(X0, T.hyper);
  if R = fail then r.orthogonalisable := false; return r; fi;
  r.orthogonalisable := true;
  r.R := R;
  r.inverts := (R*S1*R^-1 = S1^-1 and R*S2*R^-1 = S2^-1);
  r.involution := (R^2 = IdentityMat(d));
  r.det := DeterminantMat(R);
  r.in_W := (R in T.W or -R in T.W);
  r.fixed := PX.FixedLocusInPlane(T, R);
  r.fixed_minus := PX.FixedLocusInPlane(T, -R);
  return r;
end;

#############################################################################
##  Run
#############################################################################
PX.AllParentSurvivors := [];

## 1. W(T) for all 16 records
for name in PX.Order do
  T := PX.T.(name);
  surv := PX.ParentSearch(T, T.W, "W(T)", Concatenation("P-W-", name));
  Append(PX.AllParentSurvivors, surv);
od;

## 2. extended reflection-group parents
## {3,3,3} inside [3,3,5]
Print("\n\n################ EXTENDED PARENTS ################\n");
PX.H4.Setup();
if IsBound(PX.H4.found.("{3,3,3}")) then
  q := PX.H4.found.("{3,3,3}");
  Rs := List(q, i -> PX.H4.refl[i]);
  PX.CHECKEQ("embedded {3,3,3} in [3,3,5]: order of the reflection subgroup", Size(Group(Rs)), 120);
  T333 := PX.MakePolytope("{3,3,3}in[3,3,5]", Rs, PX.Orthogonal(List(Rs{[2,3,4]}, PX.NormalOf), fail), fail);
  PX.CHECKEQ("embedded {3,3,3}: marks", PX.SchlaefliData(T333).marks, [3,3,3]);
  PX.CHECKEQ("embedded {3,3,3}: f-vector", PX.FVectorOfT(T333), [5,10,10,5]);
  surv := PX.ParentSearch(T333, PX.H4.W, "[3,3,5]", "P-H4-{3,3,3}");
  Append(PX.AllParentSurvivors, surv);
  T333d := PX.Dual(T333, "{3,3,3}*in[3,3,5]");
  surv := PX.ParentSearch(T333d, PX.H4.W, "[3,3,5]", "P-H4-{3,3,3}*");
  Append(PX.AllParentSurvivors, surv);
else
  Print("no embedded {3,3,3} found in [3,3,5]\n");
fi;

## [3,4,3] = <[4,3,3], reflection in (1,1,1,1)^perp>, and [[3,4,3]] = <[3,4,3], D>
Tc := PX.T.("{4,3,3}");
F4 := Group(Concatenation(Tc.R, [PX.Reflection([1,1,1,1])]));
PX.CHECKEQ("[3,4,3] = <[4,3,3], refl(1,1,1,1)>: order", Size(F4), 1152);
T24 := PX.T.("{3,4,3}");
PX.CHECK("[3,4,3] contains the mirrors of our {3,4,3} record", ForAll(T24.R, x -> x in F4));
PX.CHECK("[3,4,3] contains [4,3,3]", ForAll(Tc.R, x -> x in F4));
Dmat := (1/Sqrt(2))*[[1,1,0,0],[1,-1,0,0],[0,0,1,1],[0,0,1,-1]];
PX.CHECK("D is orthogonal", Dmat*TransposedMat(Dmat) = IdentityMat(4));
FF4 := Group(Concatenation(GeneratorsOfGroup(F4), [Dmat]));
PX.CHECKEQ("[[3,4,3]] = <[3,4,3], D>: order", Size(FF4), 2304);
PX.CHECK("D normalises [3,4,3]", ForAll(GeneratorsOfGroup(F4), g -> Dmat*g*Dmat^-1 in F4));
for name in ["{4,3,3}", "{3,3,4}"] do
  surv := PX.ParentSearch(PX.T.(name), F4, "[3,4,3]", Concatenation("P-F4-", name)); Append(PX.AllParentSurvivors, surv);
  surv := PX.ParentSearch(PX.T.(name), FF4, "[[3,4,3]]", Concatenation("P-FF4-", name)); Append(PX.AllParentSurvivors, surv);
od;
for name in ["{3,4,3}", "{3,4,3}*"] do
  surv := PX.ParentSearch(PX.T.(name), FF4, "[[3,4,3]]", Concatenation("P-FF4-", name)); Append(PX.AllParentSurvivors, surv);
od;

## 3. normalisers of the facet groups in O(4)
Print("\n\n################ NORMALISERS N_{O(4)}(G) OF THE FACET GROUPS ################\n");
Print("## Note: by Prop. E1-E3 (theory.md, verified in alpha-complete.g) the third\n");
Print("## generator is uniquely determined by the base vertex, over ALL of O(4);\n");
Print("## the normaliser is therefore reported for information and searched only\n");
Print("## when the enumeration is cheap.\n");
PX.Normalisers := rec();
for row in [1..10] do
  name := PX.Order[2*row-1];
  T := PX.T.(name);
  nr := PX.NormaliserInO(T);
  PX.Normalisers.(name) := nr;
  Print("\n", name, ": |G| = ", Size(Group(PX.CanonicalTriple(T){[1,2]})), ", |Aut(G)| = ", nr.aut_order,
        " (inner ", nr.inner, ", outer ", nr.out, "); commutant dimension ", nr.commutant_dim,
        "; solution-space dimensions for the coset representatives ", Collected(nr.dims),
        "; realised by orthogonal matrices: ", nr.realised, "; square roots failed: ", nr.failed_sqrt, "\n");
  PX.CHECKEQ(Concatenation(name, ": the commutant of the facet group in the matrix algebra is 1-dimensional (so C_O(G) = {+-I})"),
             nr.commutant_dim, 1);
  Print("   |N_{O(4)}(G)| = 2 |Inn(G)| (realised classes) = 2 * ", nr.inn, " * ", nr.realised, " = ", nr.order_formula);
  if nr.elements <> fail then
    Print("; enumerated: ", nr.order, " elements (formula confirmed: ", nr.closed, "); contains W(T): ", nr.contains_W,
          "; rotations: ", Length(nr.rotations), "\n");
    PX.CHECK(Concatenation(name, ": the coset formula for |N_{O(4)}(G)| is confirmed by enumeration"), nr.closed);
  else
    Print("; not enumerated (too large)\n");
  fi;
  ## the rho_1-type half-turn and the geometrically regular alpha, by an exact linear solve
  rh := PX.Rho1Intertwiner(T);
  Print("   rho_1 intertwiner: solution space of dimension ", rh.dim);
  if rh.dim = 1 and IsBound(rh.R) then
    Print(", orthogonal involution: ", rh.involution, ", inverts S1 and S2: ", rh.inverts, ", det ", rh.det,
          ", lies in +-W(T): ", rh.in_W, "\n");
    PX.CHECK(Concatenation(name, ": the rho_1 intertwiner is an involution inverting S1 and S2"), rh.involution and rh.inverts);
    for pair in [ ["R", rh.R, rh.fixed], ["-R", -rh.R, rh.fixed_minus] ] do
      if Length(pair[3]) = 1 then
        a := PX.AlphaOf(T, pair[3][1][1], pair[3][1][2]);
        Print("   -> ", pair[1], " fixes the circle point (a,b) = ", pair[3][1], ", alpha = ", a.alpha);
        if a.alpha <> infinity and a.exact then Print(" ~ ", PX.Float(a.alpha)); fi;
        Print("   (geometrically regular member H_alpha of the family)\n");
      else
        Print("   -> ", pair[1], " fixes a locus of dimension ", Length(pair[3]), " in the circle plane\n");
      fi;
    od;
  else
    Print(", not usable (orthogonalisable: ", IsBound(rh.orthogonalisable) and rh.orthogonalisable = true, ")\n");
  fi;
  ## search inside N only when it was enumerated and is not already covered by W(T)
  if nr.elements <> fail and nr.order > 0 then
    surv := PX.ParentSearch(T, nr.N, "N_O(4)(G)", Concatenation("P-N-", name)); Append(PX.AllParentSurvivors, surv);
    Td := PX.T.(PX.DualName.(name));
    if ForAll(PX.CanonicalTriple(Td){[1,2]}, x -> x in nr.elements) then
      surv := PX.ParentSearch(Td, nr.N, "N_O(4)(G)", Concatenation("P-N-", Td.name)); Append(PX.AllParentSurvivors, surv);
    else
      Print("   (the dual endpoint's facet generators are not in this copy of N; its own normaliser is conjugate, so the search is not repeated)\n");
    fi;
  else
    Print("   N not enumerated: no element search here.  Level 3 for this family is settled by alpha-complete.g\n");
    Print("   (Prop. E1: the third generator is unique for each base vertex, over all of O(4)).\n");
  fi;
od;

#############################################################################
##  Compare all survivors with the canonical candidates and with each other
#############################################################################
Print("\n\n################ COMPARISON OF PARENT-SEARCH SURVIVORS ################\n");
canon := [];
for name in PX.Order do
  T := PX.T.(name); S := PX.CanonicalTriple(T);
  ps := PX.PermSetup(T.W);
  s := List(S, ps.im);
  if PX.IntersectionData(ps.P, s).holds and PX.StringRelations(s).holds then
    Add(canon, rec(name := name, G := Subgroup(ps.P, s), s := s));
  fi;
od;
for r in PX.AllParentSurvivors do
  if not r.abstract_polytope then continue; fi;
  psr := PX.PermSetup(r.Wy.Gm);
  gens := GeneratorsOfGroup(r.Wy.Gm);     # = [S1, S2, X] in this order
  sr := List([gens[1], gens[2], gens[3]], psr.im);
  Print(r.label, ":\n   |Gamma| = ", r.gamma_order, ", f-vector ", r.fvector_abstract, ", orders ", r.orders, "\n");
  for cnd in canon do
    cmp := PX.CompareTriples(Subgroup(psr.P, sr), sr, cnd.G, cnd.s);
    if cmp.isomorphic or cmp.dual then
      Print("   abstractly isomorphic to canonical ", cnd.name, " (same orientation: ", cmp.isomorphic_same_orientation,
            ", mirror: ", cmp.isomorphic_mirror, ", dual: ", cmp.dual, ")\n");
    fi;
  od;
od;

PX.Summary("parent-search.g");
if PX.nfail > 0 then QuitGap(1); fi;
Print("Done: parent-search.g\n");
