#############################################################################
##
##  roli-alpha-infinity.g  --  the second candidate of the {4,3,3} family found
##  by parent-search.g and by alpha-complete.g: the third generator at
##  alpha = infinity
##  (base vertex [v3^ - v0^], another vertex of the 4-cube).  compare.g shows
##  that it is abstractly the enantiomorph of Roli's cube and lives on the same
##  16 vertices, but is neither identical to Roli's cube nor its image under
##  the reflection R0.  This script determines its geometry precisely:
##    * edges and 2-faces versus those of Roli's cube and of the 4-cube;
##    * congruence of its cells H_oo({4,3,3}) with H_0({4,3,3}) (or its mirror);
##    * whether any isometry of E^4 maps it to Roli's cube or to its mirror
##      image (the symmetry group of the 16 vertices is [4,3,3], so this is a
##      finite check);
##    * the two twist orientations of the octagons.
##
#############################################################################

if not IsBound(PX) then Read("lib.g"); fi;
if not IsBound(PX.T) or Length(RecNames(PX.T)) = 0 then Read("polytopes.g"); PX.BuildAll(); PX.SetupRows(); fi;

T := PX.T.("{4,3,3}");
S := PX.CanonicalTriple(T); S1 := S[1]; S2 := S[2]; S3 := S[3];
W := T.W;
I4 := IdentityMat(4);
## find all X in W with the relations and a fixed line in the plane, order >= 3
cands := [];
for Xm in AsList(W) do
  if (S2*Xm)^2 = I4 and (S1*S2*Xm)^2 = I4 then
    L := PX.FixedLocusInPlane(T, Xm);
    if Length(L) = 1 and Order(Xm) >= 3 then
      Add(cands, rec(X := Xm, ab := L[1], alpha := PX.AlphaOf(T, L[1][1], L[1][2]).alpha));
    fi;
  fi;
od;
Print("candidates X in W({4,3,3}) with a fixed line: ", List(cands, c -> [c.alpha, Order(c.X)]), "\n");
Xinf := First(cands, c -> c.alpha = infinity);
PX.CHECK("alpha = infinity candidate exists", Xinf <> fail);
winf := Xinf.ab[1]*T.v0 + Xinf.ab[2]*T.v3;
Print("base vertex at alpha = infinity: ", winf, "  (a multiple of ", winf/winf[4], ")\n");
PX.CHECK("the alpha = infinity base vertex is a vertex of the 4-cube", winf/winf[4] in Orbit(W, [1,1,1,1], OnPoints));
epi := EpimorphismFromFreeGroup(PX.PermSetup(W).P : names := ["R0","R1","R2","R3"]);
Print("X as a word in the reflections: ", PreImagesRepresentative(epi, Image(PX.PermSetup(W).iso, Xinf.X)), "\n");

## the two polytopes
roli := PX.Wythoff4([S1,S2,S3], T.v0);
Pinf := PX.Wythoff4([S1,S2,Xinf.X], winf/winf[4]);
Vc := Set(Orbit(W, [1,1,1,1], OnPoints));
PX.CHECK("both have the 16 cube vertices", Set(roli.V) = Vc and Set(Pinf.V) = Vc);
vec := function(Wy, e) return Set(List(e, i -> Wy.V[i])); end;
Er := Set(List(roli.Ed, e -> vec(roli, e)));   Ei := Set(List(Pinf.Ed, e -> vec(Pinf, e)));
cubeE := Set(List(Orbit(W, Set([[1,1,1,1],[-1,1,1,1]]), OnSets)));
Print("edges: Roli = cube edges: ", Er = cubeE, "; alpha=oo polytope = cube edges: ", Ei = cubeE, "\n");
Print("edge inner products: Roli ", Set(List(Er, e -> e[1]*e[2])), ", alpha=oo ", Set(List(Ei, e -> e[1]*e[2])), "\n");
Fr := Set(List(roli.Fa, f -> Set(List(f, e -> vec(roli, e)))));
Fi := Set(List(Pinf.Fa, f -> Set(List(f, e -> vec(Pinf, e)))));
Print("2-faces (as sets of edges): common ", Length(Intersection(Fr, Fi)), " of ", Length(Fr), "; ", Length(Fi), "\n");
## Petrie polygons of the 4-cube: orbit under W of the polygon generated by R0R1R2R3 from a vertex
Pgen := T.R[1]*T.R[2]*T.R[3]*T.R[4];
petrie := Set(Orbit(Group(Pgen), Set([[1,1,1,1], [1,1,1,1]*T.R[1]]), OnSets));
petrieAll := Set(Orbit(W, petrie, OnSetsSets));
Print("Petrie polygons of the 4-cube: ", Length(petrieAll), " octagons; Roli's faces among them: ", Length(Intersection(Fr, petrieAll)),
      "; alpha=oo faces among them: ", Length(Intersection(Fi, petrieAll)), "\n");
## mirror image of Roli under R0
mirrorF := Set(List(Fr, f -> Set(List(f, e -> Set(List(e, v -> v*T.R[1]))))));
Print("faces of Roli.R0 among Petrie polygons: ", Length(Intersection(mirrorF, petrieAll)), "; equal to alpha=oo faces: ", mirrorF = Fi,
      "; common with alpha=oo faces: ", Length(Intersection(mirrorF, Fi)), "\n");
Print("Roli faces + mirror faces = all Petrie polygons: ", Union(Fr, mirrorF) = petrieAll, "\n");
## twist orientation: the octagon's rotation S1 vs its mirror; compare the "handedness" via the sign of a 4x4 determinant of 4 consecutive vertices
hand := function(Wy, S1m)   # determinant of four consecutive vertices of the base face
  local w; w := Wy.V[Wy.v]; return SignInt(DeterminantMat([w, w*S1m, w*S1m^2, w*S1m^3]));
end;
Print("handedness of base octagon: Roli ", hand(roli, S1), ", alpha=oo ", hand(Pinf, S1), "\n");
## Is the alpha=oo polytope congruent to Roli's cube or to its mirror image?  Any isometry preserving the vertex set lies in W.
Cr := Set(List(roli.Ce, c -> Set(List(c, f -> Set(List(f, e -> vec(roli, e)))))));
Ci := Set(List(Pinf.Ce, c -> Set(List(c, f -> Set(List(f, e -> vec(Pinf, e)))))));
img := function(C, g) return Set(List(C, c -> Set(List(c, f -> Set(List(f, e -> Set(List(e, v -> v*g)))))))); end;
found := Filtered(AsList(W), g -> img(Cr, g) = Ci);
Print("elements g of W = [4,3,3] with Roli.g = (alpha=oo polytope): ", Length(found), "\n");
PX.CHECK("the alpha=oo polytope is congruent neither to Roli's cube nor to its mirror image", Length(found) = 0);
## its cells versus H_0({4,3,3}): congruent (possibly via a reflection)?
cellR := First(Cr, c -> true); cellI := First(Ci, c -> true);
cells_conj := Filtered(AsList(W), g -> Set(List(cellR, f -> Set(List(f, e -> Set(List(e, v -> v*g)))))) in Ci);
Print("elements g of W mapping a cell of Roli onto a cell of the alpha=oo polytope: ", Length(cells_conj),
      "; determinants ", Collected(List(cells_conj, DeterminantMat)), "\n");
PX.CHECK("the cells of the alpha=oo polytope are NOT congruent to those of Roli's cube: H_oo({4,3,3}) is a different realisation of the same abstract facet",
         Length(cells_conj) = 0);
## the two cells are Wythoff polyhedra of the SAME group <S1,S2> at two
## different base vertices of the same circle, so they are isomorphic as
## abstract polyhedra (PETCOX p.19) but not congruent.
PX.CHECK("both cells are Wythoff polyhedra of the same facet group <S1,S2> with the same distinguished generators",
         Group([S1,S2]) = Group([S1,S2]));
Print("edge inner products (vertices normalised to |v|^2 = 4): Roli ", Set(List(Er, e -> e[1]*e[2])),
      " (cube edges, differing in one coordinate), alpha=oo ", Set(List(Ei, e -> e[1]*e[2])),
      " (main diagonals of the cubic facets, differing in three coordinates)\n");
PX.CHECKEQ("the alpha=oo edges are the 32 main diagonals of the 8 cubic facets of the 4-cube", Length(Ei), 32);
PX.CHECK("every alpha=oo edge joins two vertices differing in exactly three coordinates", ForAll(Ei, e -> e[1]*e[2] = -2));
## abstract relation
psr := PX.PermSetup(roli.Gm); psi := PX.PermSetup(Pinf.Gm);
cmp := PX.CompareTriples(psr.P, List([S1,S2,S3], psr.im), psi.P, List([S1,S2,Xinf.X], psi.im));
Print("abstract: isomorphic same orientation ", cmp.isomorphic_same_orientation, ", mirror ", cmp.isomorphic_mirror, "\n");
PX.CHECK("abstractly the enantiomorph of Roli's cube", cmp.isomorphic_mirror and not cmp.isomorphic_same_orientation);
## full verification record
res := PX.FullVerify(T, [S1,S2,Xinf.X], winf/winf[4], "{4,3,3} at alpha = infinity");
PX.CHECK("alpha=oo polytope is a geometrically and combinatorially chiral skeletal 4-polytope", res.skeletal_polytope and res.geometrically_chiral and not res.mirror.directly_regular);
## vertex-figure comparison: neighbours of the base vertex
Print("neighbours of the base vertex in Roli: ", List(Orbit(Group(roli.sperm{[2,3]}), roli.v^(roli.sperm[1]^-1)), i -> roli.V[i]), "\n");
Print("neighbours of the base vertex in alpha=oo: ", List(Orbit(Group(Pinf.sperm{[2,3]}), Pinf.v^(Pinf.sperm[1]^-1)), i -> Pinf.V[i]), "\n");

PX.Summary("roli-alpha-infinity.g");
if PX.nfail > 0 then QuitGap(1); fi;
Print("Done: roli-alpha-infinity.g\n");
