#############################################################################
##
##  l3-audit.g  --  fresh-session Fable audit (audits/fable-ultra):
##  INDEPENDENT re-derivation of the "Level 3" analysis of the producer's
##  gap/alpha-complete.g, over the FULL list of candidate orders of the third
##  generator, including the vertex-figure case (q,m) = (5,5) that the
##  producer excludes a priori by the "spherical triangle" inequality
##  1/2 + 1/q + 1/m > 1.  That inequality characterises FINITE triangle
##  groups, not finite quotients: A5 = <(12345),(12354)> is generated by two
##  rotations of order 5 with involutory product (the great dodecahedron
##  {5,5/2} / small stellated dodecahedron {5/2,5}), so (q,m) = (5,5) must be
##  tested for the four PETCOX rows with q = 5 (rows 5,6,9,10).
##
##  What is reused from the producer: ONLY the reflection matrices of the 16
##  regular 4-polytopes (gap/lib.g, gap/polytopes.g), which the producer's
##  census-audit.g checks against the printed tetrahedra of petcox.pdf.
##  Everything decisive below (invariant planes, half-turn A(t), X(t), trace
##  polynomial, factorisation, exact roots, Sturm counts, Kronecker-Weber
##  test, finiteness tests, intersection condition, f-vectors, mirror test,
##  stabilisers) is re-implemented here with different code.
##
##  Run from audits/fable-ultra/scripts:
##      gap -q -A --quitonbreak l3-audit.g < /dev/null
##  Writes ../logs/audit-runs/l3-audit-rows.tsv
##
#############################################################################

Read("../../../gap/lib.g");
Read("../../../gap/polytopes.g");
PX.BuildAll(); PX.SetupRows();
SizeScreen([ 4096, ]);

AU := rec(npass := 0, nfail := 0, failed := []);
AU.CHECK := function(name, val)
  if val = true then AU.npass := AU.npass + 1; Print("AU-PASS  ", name, "\n");
  else AU.nfail := AU.nfail + 1; Add(AU.failed, name); Print("AU-FAIL  ", name, "   (got ", val, ")\n"); fi;
end;
AU.CHECKEQ := function(name, a, b)
  if a = b then AU.npass := AU.npass + 1; Print("AU-PASS  ", name, " = ", b, "\n");
  else AU.nfail := AU.nfail + 1; Add(AU.failed, name); Print("AU-FAIL  ", name, "   (expected ", b, ", got ", a, ")\n"); fi;
end;

K := CF(5);
t := Indeterminate(K, "t");
R := PolynomialRing(K, [t]);
sq5 := Sqrt(5);
AU.PI := 3.14159265358979323846;

AU.Float := function(x) local n, c, s, k;
  if x = infinity then return infinity; fi;
  if IsRat(x) then return Float(x); fi;
  n := Conductor(x); c := CoeffsCyc(x, n); s := 0.0;
  for k in [1..n] do if c[k] <> 0 then s := s + Float(c[k])*Cos(2*AU.PI*(k-1)/n); fi; od;
  return s;
end;
AU.SignRat := function(a) return SignInt(NumeratorRat(a)); end;
## x = a + b sqrt5 with a, b rational, or fail
AU.Q5 := function(x) local a, b;
  if IsRat(x) then return [x, 0]; fi;
  a := (x + GaloisCyc(x, 2))/2; b := (x - GaloisCyc(x, 2))/(2*sq5);
  if IsRat(a) and IsRat(b) and a + b*sq5 = x then return [a, b]; fi;
  return fail;
end;
## exact sign of an element of Q(sqrt5)
AU.Sign := function(x) local ab, a, b;
  ab := AU.Q5(x); if ab = fail then return fail; fi; a := ab[1]; b := ab[2];
  if b = 0 then return AU.SignRat(a); fi;
  if a = 0 then return AU.SignRat(b); fi;
  if AU.SignRat(a) = AU.SignRat(b) then return AU.SignRat(a); fi;
  if a > 0 then
    if a^2 > 5*b^2 then return 1; elif a^2 = 5*b^2 then return 0; else return -1; fi;
  else
    if 5*b^2 > a^2 then return 1; elif 5*b^2 = a^2 then return 0; else return -1; fi;
  fi;
end;
AU.IsReal := function(x) return GaloisCyc(x, -1) = x; end;
AU.Deg := function(f) return DegreeOfLaurentPolynomial(f); end;
AU.Coeffs := function(f) return CoefficientsOfUnivariatePolynomial(f); end;

## exact number of distinct real roots of f (coefficients in Q(sqrt5)) by Sturm's theorem
AU.SturmCount := function(f) local g, seq, r, sp, sn, lc, d, V, h;
  g := Gcd(R, f, Derivative(f));
  f := Quotient(R, f, g);                  # square-free part
  seq := [ f, Derivative(f) ];
  while AU.Deg(seq[Length(seq)]) > 0 do
    r := -EuclideanRemainder(R, seq[Length(seq)-1], seq[Length(seq)]);
    if IsZero(r) then break; fi;
    Add(seq, r);
  od;
  sp := []; sn := [];
  for h in seq do
    if IsZero(h) then continue; fi;
    lc := LeadingCoefficient(h); d := AU.Deg(h);
    if AU.Sign(lc) = fail then return fail; fi;
    Add(sp, AU.Sign(lc));
    if d mod 2 = 0 then Add(sn, AU.Sign(lc)); else Add(sn, -AU.Sign(lc)); fi;
  od;
  V := function(l) local c, i; c := 0;
    for i in [1..Length(l)-1] do if l[i]*l[i+1] < 0 then c := c + 1; fi; od; return c; end;
  return V(sn) - V(sp);
end;

## exact square root of a nonnegative element D of Q(sqrt5), in Q(sqrt5) or a
## small cyclotomic field; fail if none found (then decide with AU.KWAbelian)
AU.SqrtExact := function(D) local ab, a, b, disc, z, c, dd, y, n, pol, roots, r;
  ab := AU.Q5(D); if ab = fail then return fail; fi; a := ab[1]; b := ab[2];
  if D = 0 then return 0; fi;
  if b = 0 then
    y := Sqrt(a); if IsRat(y) then return y; fi;
    if a > 0 then y := Sqrt(a/5); if IsRat(y) then return y*sq5; fi; fi;
  else
    disc := a^2 - 5*b^2;
    if disc >= 0 and IsRat(Sqrt(disc)) then
      for z in [ (a + Sqrt(disc))/2, (a - Sqrt(disc))/2 ] do
        if z >= 0 and IsRat(Sqrt(z)) then
          c := Sqrt(z);
          if c <> 0 then dd := b/(2*c); y := c + dd*sq5; if y^2 = D then return y; fi; fi;
        fi;
      od;
    fi;
  fi;
  for n in [ 20, 40, 60, 120, 15, 30, 24, 8, 12 ] do
    pol := UnivariatePolynomial(CF(Lcm(n,5)), [ -D, 0, 1 ]);
    roots := RootsOfUPol(CF(Lcm(n,5)), pol);
    for r in roots do
      if r^2 = D and AU.IsReal(r) and AU.Sign(r*GaloisCyc(r,-1)) <> fail then return r; fi;
    od;
  od;
  return fail;
end;
## Kronecker-Weber: is Q(sqrt5, sqrt D)/Q abelian?  iff D*sigma(D) is a square in Q(sqrt5)
AU.KWAbelian := function(D) local N;
  N := D*GaloisCyc(D, 2);
  if not IsRat(N) then return fail; fi;
  if N = 0 then return true; fi;
  if N < 0 then return false; fi;
  if IsRat(Sqrt(N)) then return true; fi;
  if IsRat(Sqrt(N/5)) then return true; fi;
  return false;
end;
## value of the rational function P/Q at a root of the quadratic f: [c0, c1] with value c0 + c1 t
AU.ModFactor := function(P, Q, f) local Pr, Qr, g, inv, res, cf;
  Pr := EuclideanRemainder(R, P, f); Qr := EuclideanRemainder(R, Q, f);
  if IsZero(Qr) then return fail; fi;
  g := GcdRepresentation(R, Qr, f);
  if not IsOne(EuclideanRemainder(R, g[1]*Qr + g[2]*f, f)) and Gcd(R, Qr, f) <> One(R) then return fail; fi;
  inv := g[1];
  res := EuclideanRemainder(R, Pr*inv, f);
  cf := ShallowCopy(AU.Coeffs(res));
  while Length(cf) < 2 do Add(cf, Zero(K)); od;
  return cf{[1,2]};
end;

## invariant planes of a twist S (own implementation): for k = 1..p/2 the
## kernel of S^2 - 2cos(2 pi k/p) S + I
AU.Planes := function(S, dim) local p, res, k, c, N;
  p := Order(S); res := [];
  for k in [1..Int(p/2)] do
    c := E(p)^k + E(p)^(-k);
    N := NullspaceMat(S^2 - c*S + IdentityMat(dim));
    if Length(N) > 0 then
      Add(res, rec(k := k, B := N, dim := Length(N),
                   P := TransposedMat(N)*(N*TransposedMat(N))^-1*N));
    fi;
  od;
  return res;
end;
AU.Proj := function(u) return TransposedMat([u])*[u]/(u*u); end;

## orbit of w under the matrices gens with a cap; returns rec(finite, orbit)
AU.Orbit := function(gens, w, cap) local orb, i, g, im, seen;
  orb := [ w ]; i := 1;
  while i <= Length(orb) do
    for g in gens do
      im := orb[i]*g;
      if not im in orb then
        if Length(orb) >= cap then return rec(finite := false, size := Length(orb), orbit := orb); fi;
        Add(orb, im);
      fi;
    od;
    i := i + 1;
  od;
  return rec(finite := true, size := Length(orb), orbit := orb);
end;
AU.OnSSS := function(cell, g) return Set(List(cell, x -> OnSetsSets(x, g))); end;

## full geometric/abstract test of a triple S = [S1,S2,X] at base vertex w
## (assumes the orbit of w is finite and spans the effective space)
AU.Test := function(S, w, effdim) local orb, V, pos, perms, P, s, e, f, c, Ed, Fa, Ce, r, I3, mir, hom, F3V, nb;
  r := rec();
  orb := AU.Orbit(S, w, 8000);
  r.orbit_finite := orb.finite; r.nV := orb.size;
  if not orb.finite then return r; fi;
  V := orb.orbit; pos := x -> Position(V, x);
  r.span := RankMat(V);
  perms := List(S, g -> PermList(List(V, v -> pos(v*g))));
  if fail in perms then r.perm_fail := true; return r; fi;
  P := Group(perms); s := perms;
  r.order := Size(P);
  r.orders := List(s, Order);
  r.relations := (Order(s[1]*s[2]) = 2 and Order(s[2]*s[3]) = 2 and Order(s[1]*s[2]*s[3]) = 2);
  I3 := Intersection(Subgroup(P, s{[1,2]}), Subgroup(P, s{[2,3]}));
  r.ip12 := IsTrivial(Intersection(Subgroup(P,[s[1]]), Subgroup(P,[s[2]])));
  r.ip23 := IsTrivial(Intersection(Subgroup(P,[s[2]]), Subgroup(P,[s[3]])));
  r.defect := Size(I3)/Order(s[2]);
  r.ip := r.ip12 and r.ip23 and (I3 = Subgroup(P, [s[2]]));
  r.G_order := Size(Subgroup(P, s{[1,2]})); r.vf_order := Size(Subgroup(P, s{[2,3]}));
  r.fvec_coset := [ Index(P, Subgroup(P, s{[2,3]})), Index(P, Subgroup(P, [s[3], s[1]*s[2]])),
                    Index(P, Subgroup(P, [s[1], s[2]*s[3]])), Index(P, Subgroup(P, s{[1,2]})) ];
  hom := GroupHomomorphismByImages(P, P, s, [ s[1]^-1, s[1]^2*s[2], s[3] ]);
  r.directly_regular := (hom <> fail and IsBijective(hom));
  if not r.ip then return r; fi;
  e := Set([ pos(w), pos(w*S[1]^-1) ]);
  f := Set(Orbit(Group(s[1]), e, OnSets));
  c := Set(Orbit(Group(s{[1,2]}), f, OnSetsSets));
  Ed := Orbit(P, e, OnSets); Fa := Orbit(P, f, OnSetsSets); Ce := Orbit(P, c, AU.OnSSS);
  r.fvec_geom := [ Length(V), Length(Ed), Length(Fa), Length(Ce) ];
  r.face_size := Length(f); r.faces_per_cell := Length(c);
  r.stab := [ Stabilizer(P, pos(w), OnPoints) = Subgroup(P, s{[2,3]}),
              Stabilizer(P, e, OnSets) = Subgroup(P, [s[3], s[1]*s[2]]),
              Stabilizer(P, f, OnSetsSets) = Subgroup(P, [s[1], s[2]*s[3]]),
              Stabilizer(P, c, AU.OnSSS) = Subgroup(P, s{[1,2]}) ];
  r.diamond := [ Number(f, x -> pos(w) in x), Number(c, x -> e in x), Number(Ce, x -> f in x) ];
  r.face_span := RankMat(List(f, x -> V[x[1]]));
  ## facet polyhedron vertex count vs abstract |G|/q (collapse test)
  F3V := AU.Orbit(S{[1,2]}, w, 8000);
  r.facet_nV := F3V.size; r.facet_abstract_nV := r.G_order/Order(s[2]);
  nb := Orbit(Group(s{[2,3]}), pos(w*S[1]^-1), OnPoints);
  r.n_neighbours := Length(nb); r.vf_abstract_nV := r.vf_order/Order(s[3]);
  r.faithful := (r.fvec_geom = r.fvec_coset) and ForAll(r.stab, x -> x) and (r.span = effdim)
                and (r.facet_nV = r.facet_abstract_nV) and (r.n_neighbours = r.vf_abstract_nV);
  r.skeletal := r.faithful and r.diamond = [2,2,2] and r.ip and r.relations and Order(s[3]) >= 3;
  r.geom_chiral := r.skeletal and (r.face_span = effdim);   # Prop. D1 hypothesis
  return r;
end;

## admissible orders m of X and their trace targets: ALL of 2..12 that could
## conceivably occur, not only the spherical ones
AU.Targets := [];
for m in [2,3,4,5,6,10] do   # traces 2+2cos(2 pi k/m) lie in Q(sqrt5) exactly for these m; m = 8, 12 (traces in Q(sqrt2), Q(sqrt3)) are excluded by Prop. E2 anyway
  for k in [1..Int(m/2)] do
    if Gcd(k, m) = 1 then Add(AU.Targets, rec(m := m, k := k, c := 2 + E(m)^k + E(m)^(-k))); fi;
  od;
od;

AU.TSV := "../logs/audit-runs/l3-audit-rows.tsv";
PrintTo(AU.TSV, JoinStringsWithSeparator([ "row","T","q","m_target","k","t_exact","t_float","alpha_float","X_order","tr_X",
  "vf_orbit_finite","vf_group_order","vf_structure","gamma_finite","gamma_order","relations","ip","defect",
  "fvec_coset","fvec_geom","directly_regular","faithful","skeletal","geom_chiral","verdict" ], "\t"), "\n");
AU.Rows := [];

AU.AnalyseRow := function(row)
  local name, T, S1, S2, d, hyper, planes, wpol, w1, w2, d1, d2, dh, N, tau, tg, poly, facs, f, cf, nreal, exact_roots, killed,
        unresolved, nonreal, deg, b, c, D, sg, y, roots, r0, total_sturm, acc, res, lab, w, A, X, u, vfo, vforb, Hp, vfstruct,
        alpha, rho2, rho, tst, verdict, fields, gs, g, ab, witness, mm, Xord, effdim, allroots, q, kk, ordcheck, Pv, hv;
  name := PX.Order[2*row-1];
  T := PX.T.(name);
  S1 := T.R[1]*T.R[2]*T.R[4]*T.R[3];  S2 := T.R[3]*T.R[2];
  d := T.dim; hyper := T.hyper; effdim := 4;
  q := Order(S2);
  Print("\n\n############################################################\n");
  Print("## AUDIT Level 3, row ", row, ": T = ", name, ", dim ", d, ", p = ord(S1) = ", Order(S1), ", q = ord(S2) = ", q, "\n");
  Print("############################################################\n");
  planes := AU.Planes(S1, d);
  Print("invariant planes of S1: k = ", List(planes, x -> x.k), ", dims ", List(planes, x -> x.dim), "\n");
  AU.CHECK(Concatenation(name, ": exactly two invariant planes, each 2-dimensional"), Length(planes) = 2 and ForAll(planes, x -> x.dim = 2));
  AU.CHECK(Concatenation(name, ": rotation angles distinct and non-opposite"), planes[1].k <> planes[2].k and (planes[1].k + planes[2].k) mod Order(S1) <> 0);
  AU.CHECK(Concatenation(name, ": neither angle is pi"), ForAll(planes, x -> 2*x.k <> Order(S1)));
  AU.CHECK(Concatenation(name, ": planes mutually orthogonal"), ForAll(planes[1].B, a -> ForAll(planes[2].B, bb -> a*bb = 0)));
  AU.CHECK(Concatenation(name, ": S1 has no fixed vector in the effective 4-space"),
           Length(NullspaceMat(S1 - IdentityMat(d))) = (d - 4));
  ## the circle span(v0,v3) avoids both planes
  for f in planes do
    AU.CHECK(Concatenation(name, ": PETCOX circle avoids the invariant plane k = ", String(f.k)),
             Length(NullspaceMat([ T.v0*(IdentityMat(d) - f.P), T.v3*(IdentityMat(d) - f.P) ])) = 0);
  od;
  ## w(t) = t v0 + v3;  A(t) = 2(w1^T w1/d1 + w2^T w2/d2 [+ h^T h/dh]) - I = N(t)/(d1 d2 dh)
  wpol := List([1..d], i -> t*T.v0[i] + T.v3[i]);
  w1 := wpol*planes[1].P; w2 := wpol*planes[2].P;
  d1 := w1*w1; d2 := w2*w2;
  if hyper <> fail then dh := hyper*hyper*One(R); else dh := One(R); fi;
  N := 2*( TransposedMat([w1])*[w1]*d2*dh + TransposedMat([w2])*[w2]*d1*dh );
  if hyper <> fail then N := N + 2*TransposedMat([hyper])*[hyper]*d1*d2; fi;
  N := N - d1*d2*dh*IdentityMat(d);
  tau := Trace(S2^-1*N);
  Print("deg d1 = ", AU.Deg(d1), ", deg d2 = ", AU.Deg(d2), ", deg tau = ", AU.Deg(tau), "\n");
  ## d1, d2 individually may live over Q(sqrt2) or Q(sqrt3) (the two planes are Galois conjugate); their product is in Q(sqrt5)[t]
  if ForAll(AU.Coeffs(d1*d2), x -> x in CF(5)) then
    AU.CHECK(Concatenation(name, ": d1*d2 has no real zero (Sturm), so A(t) is defined for every real t"), AU.SturmCount(d1*d2) = 0);
  else Print("(d1*d2 not over CF(5); Sturm check skipped -- the linear 'circle avoids the planes' check above covers it)\n"); fi;
  AU.CHECK(Concatenation(name, ": the trace numerator tau and d1*d2 have coefficients in CF(5) = Q(zeta_5)"), ForAll(AU.Coeffs(tau), x -> x in CF(5)) and ForAll(AU.Coeffs(d1*d2), x -> x in CF(5)));
  rho2 := (T.v0*T.v0)/(T.v3*T.v3); rho := AU.SqrtExact(rho2);
  allroots := [];
  for tg in AU.Targets do
    c := tg.c; if hyper <> fail then c := c + 1; fi;
    poly := tau - c*d1*d2*dh;
    Print("\n-- target ord(X) = ", tg.m, " (k = ", tg.k, "), tr(X) = ", c, " ~ ", AU.Float(c), "; degree ", AU.Deg(poly));
    if IsZero(poly) then Print("  IDENTICALLY ZERO (unexpected)\n"); AU.CHECK(Concatenation(name, ": target polynomial not identically zero"), false); continue; fi;
    total_sturm := AU.SturmCount(poly);
    Print("; exact number of distinct real roots (Sturm) = ", total_sturm, "\n");
    facs := Factors(R, poly);
    facs := Set(List(facs, f -> f/LeadingCoefficient(f)));      # distinct monic irreducible factors (Sturm counts distinct roots)
    exact_roots := []; killed := 0; unresolved := 0; nonreal := 0; acc := 0;
    for f in facs do
      deg := AU.Deg(f);
      if deg <= 0 then continue; fi;
      cf := AU.Coeffs(f);
      f := f/cf[Length(cf)]; cf := AU.Coeffs(f);       # monic
      if not ForAll(cf, AU.IsReal) then
        nonreal := nonreal + 1;
        Print("   factor of degree ", deg, " with NON-REAL coefficients (its complex-conjugate factor also occurs; no real roots): ", f, "\n");
        continue;
      fi;
      if deg = 1 then
        r0 := -cf[1]; if not r0 in exact_roots then Add(exact_roots, r0); acc := acc + 1; fi;
        Print("   linear factor: t = ", r0, " ~ ", AU.Float(r0), "\n");
      elif deg = 2 then
        b := cf[2]; c := cf[1]; D := b^2 - 4*c; sg := AU.Sign(D);
        Print("   quadratic factor ", f, ": discriminant D = ", D, " ~ ", AU.Float(D), ", sign ", sg, "\n");
        if sg = fail then unresolved := unresolved + 1; Print("      UNRESOLVED: discriminant not in Q(sqrt5)\n");
        elif sg < 0 then Print("      no real roots\n");
        elif sg = 0 then r0 := -b/2; Add(exact_roots, r0); acc := acc + 1; Print("      double root t = ", r0, "\n");
        else
          y := AU.SqrtExact(D);
          if y <> fail then
            for r0 in [ (-b+y)/2, (-b-y)/2 ] do Add(exact_roots, r0); acc := acc + 1; Print("      exact root t = ", r0, " ~ ", AU.Float(r0), "\n"); od;
          else
            ab := AU.KWAbelian(D);
            Print("      sqrt(D) not found in a small cyclotomic field; Q(sqrt5,sqrt D)/Q abelian (KW norm test, N = ", D*GaloisCyc(D,2), "): ", ab, "\n");
            if ab = false then
              witness := fail;
              for g in [ S1, S1^2, S2, S1*S2, S1^3, S1^-1*S2, S2*S1, S1^2*S2 ] do
                mm := AU.ModFactor(Trace(g*S2^-1*N), d1*d2*dh, f);
                if mm <> fail and not IsZero(mm[2]) then witness := mm; break; fi;
              od;
              if witness <> fail then
                killed := killed + 1; acc := acc + 2;
                Print("      KILLED (Kronecker-Weber): some tr(g X) = ", witness[1], " + (", witness[2], ") t with nonzero t-coefficient, hence not in any cyclotomic field: Gamma infinite\n");
              else
                unresolved := unresolved + 1; Print("      UNRESOLVED: no trace witness found\n");
              fi;
            else
              unresolved := unresolved + 1; Print("      UNRESOLVED: abelian extension but square root not located\n");
            fi;
          fi;
        fi;
      else
        nreal := AU.SturmCount(f);
        Print("   irreducible factor of degree ", deg, " with ", nreal, " real roots: ", f, "\n");
        if nreal <> 0 then unresolved := unresolved + 1; else Print("      no real roots\n"); fi;
      fi;
    od;
    AU.CHECK(Concatenation(name, " m=", String(tg.m), " k=", String(tg.k), ": every real root accounted for (exact roots + KW-killed = Sturm count, nothing unresolved)"),
             acc = total_sturm and unresolved = 0);
    for r0 in exact_roots do Add(allroots, rec(tg := tg, t := r0)); od;
  od;
  ## t = infinity (w = v0, alpha = 0)
  Add(allroots, rec(tg := rec(m := "inf", k := "-", c := "-"), t := infinity));
  Print("\n-- verification of every exact real root (", Length(allroots), " base vertices incl. t = infinity) --\n");
  for res in allroots do
    if res.t = infinity then w := T.v0; else w := res.t*T.v0 + T.v3; fi;
    if w = 0*w then Print("   t = ", res.t, ": w = 0, skipped\n"); continue; fi;
    if res.t = infinity then alpha := 0.0;
    elif rho <> fail then
      if 1 + res.t*rho = 0 then alpha := infinity; else alpha := AU.Float(1/(1 + res.t*rho)); fi;
    else alpha := 1/(1 + AU.Float(res.t)*Sqrt(AU.Float(rho2))); fi;
    lab := Concatenation("row ", String(row), " ", name, " m=", String(res.tg.m), " k=", String(res.tg.k), " t=", String(res.t));
    w1 := w*planes[1].P; w2 := w*planes[2].P;
    if w1 = 0*w1 or w2 = 0*w2 then Print("   ", lab, ": degenerate (w in an invariant plane)\n"); continue; fi;
    A := 2*(AU.Proj(w1) + AU.Proj(w2)) - IdentityMat(d);
    if hyper <> fail then A := A + 2*AU.Proj(hyper); fi;
    X := S2^-1*A;
    AU.CHECK(Concatenation(lab, ": A is an orthogonal involution inverting S1 and fixing w"),
             A*TransposedMat(A) = IdentityMat(d) and A^2 = IdentityMat(d) and A*S1*A = S1^-1 and w*A = w);
    AU.CHECK(Concatenation(lab, ": (S2 X)^2 = (S1 S2 X)^2 = 1, X fixes w and w S1^-1, det X = 1"),
             (S2*X)^2 = IdentityMat(d) and (S1*S2*X)^2 = IdentityMat(d) and w*X = w and w*S1^-1*X = w*S1^-1 and DeterminantMat(X) = 1);
    ## order of X: theory says it is finite with tr X = target
    Xord := fail;
    for mm in [1..60] do if X^mm = IdentityMat(d) then Xord := mm; break; fi; od;
    Print("   ", lab, ": alpha ~ ", alpha, ", ord(X) = ", Xord, ", tr(X) = ", Trace(X), "\n");
    if res.tg.m <> "inf" then AU.CHECKEQ(Concatenation(lab, ": ord(X) equals the target m"), Xord, res.tg.m); fi;
    verdict := "";
    ## vertex-figure group finiteness: orbit of the neighbour u = w S1^-1 under <S2, X>
    u := w*S1^-1;
    vforb := AU.Orbit([S2, X], u, 400);
    vfo := fail; vfstruct := "-";
    if vforb.finite then
      Pv := Group(List([S2,X], g -> PermList(List(vforb.orbit, v -> Position(vforb.orbit, v*g)))));
      hv := RankMat(vforb.orbit);
      if hv >= 3 then vfo := Size(Pv); vfstruct := StructureDescription(Pv); fi;
    fi;
    Print("      vertex-figure group <S2,X>: neighbour orbit finite: ", vforb.finite, " (size ", vforb.size, "), order ", vfo, " ", vfstruct, "\n");
    if Xord = fail or Xord < 3 then
      verdict := "REJECTED: ord(X) < 3 (degenerate)";
      tst := rec();
    elif not vforb.finite then
      verdict := "REJECTED: <S2,X> infinite (vertex-figure group not finite): no discrete polytope";
      tst := rec();
    else
      tst := AU.Test([S1, S2, X], w, effdim);
      if not tst.orbit_finite then
        verdict := "REJECTED: vertex orbit exceeds 7200 (Gamma infinite by the quaternionic bound)";
      elif not tst.ip then
        verdict := Concatenation("REJECTED: intersection condition fails (defect ", String(tst.defect), ")");
      elif not tst.skeletal then
        verdict := "REJECTED: abstract polytope but realisation not a faithful skeletal 4-polytope";
      else
        verdict := "SURVIVOR: faithful skeletal 4-polytope";
        if tst.geom_chiral then verdict := Concatenation(verdict, ", geometrically chiral (2-face spans E^4)"); fi;
        if tst.directly_regular then verdict := Concatenation(verdict, ", directly regular abstractly"); else verdict := Concatenation(verdict, ", combinatorially chiral"); fi;
      fi;
      Print("      Gamma: orbit finite ", tst.orbit_finite, ", |V| = ", tst.nV);
      if tst.orbit_finite then
        Print(", |Gamma| = ", tst.order, ", orders ", tst.orders, ", relations ", tst.relations, ", IP ", tst.ip, " (defect ", tst.defect, "), coset f-vector ", tst.fvec_coset, ", directly regular ", tst.directly_regular);
        if IsBound(tst.fvec_geom) then Print(", geometric f-vector ", tst.fvec_geom, ", stabilisers ", tst.stab, ", diamond ", tst.diamond, ", span ", tst.span, ", 2-face span ", tst.face_span, ", faithful ", tst.faithful, ", skeletal ", tst.skeletal); fi;
      fi;
      Print("\n");
    fi;
    Print("      => ", verdict, "\n");
    fields := [ row, name, q, res.tg.m, res.tg.k, res.t, AU.Float(res.t), alpha, Xord, Trace(X), vforb.finite, vfo, vfstruct ];
    if IsBound(tst.orbit_finite) then
      Add(fields, tst.orbit_finite);
      if tst.orbit_finite then
        Append(fields, [ tst.order, tst.relations, tst.ip, tst.defect, tst.fvec_coset ]);
        if IsBound(tst.fvec_geom) then Append(fields, [ tst.fvec_geom, tst.directly_regular, tst.faithful, tst.skeletal, tst.geom_chiral ]);
        else Append(fields, [ "-", tst.directly_regular, "-", "-", "-" ]); fi;
      else Append(fields, [ "-", "-", "-", "-", "-", "-", "-", "-", "-", "-" ]); fi;
    else Append(fields, [ "-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-" ]); fi;
    Add(fields, verdict);
    AppendTo(AU.TSV, JoinStringsWithSeparator(List(fields, String), "\t"), "\n");
    Add(AU.Rows, rec(row := row, T := name, m := res.tg.m, k := res.tg.k, t := res.t, alpha := alpha, verdict := verdict, tst := tst));
  od;
end;

for row in [1..10] do AU.AnalyseRow(row); od;

Print("\n\n############################################################\n## AUDIT SUMMARY\n############################################################\n");
surv := Filtered(AU.Rows, r -> StartsWith(r.verdict, "SURVIVOR"));
Print("survivors (faithful skeletal 4-polytopes) found by the independent Level-3 sweep: ", Length(surv), "\n");
for r in surv do Print("  row ", r.row, " ", r.T, " m=", r.m, " k=", r.k, " t=", r.t, " alpha~", r.alpha, " |Gamma|=", r.tst.order, " f=", r.tst.fvec_coset, " dr=", r.tst.directly_regular, "\n"); od;
Print("\nsurvivors with vertex-figure type (q,m) = (5,5) [the case the producer excluded a priori]: ",
      Number(surv, r -> r.m = 5 and Order(PX.T.(r.T).R[3]*PX.T.(r.T).R[2]) = 5), "\n");
Print("survivors with ord(X) not in {3,4,5}: ", Number(surv, r -> not r.m in [3,4,5]), "\n");
AU.CHECKEQ("number of survivors of the independent sweep", Length(surv), 24);
AU.CHECKEQ("survivors with a (5,5) vertex-figure", Number(surv, r -> r.m = 5 and Order(PX.T.(r.T).R[3]*PX.T.(r.T).R[2]) = 5), 0);
Print("\nl3-audit.g: ", AU.npass, " passed, ", AU.nfail, " failed.\n");
if AU.nfail > 0 then Print("FAILED: ", AU.failed, "\n"); fi;
Print("Done: l3-audit.g\n");
