#############################################################################
##  misc-audit.g -- fresh-session Fable audit: small independent certificates.
##  (a) A5 is generated by two elements of order 5 with involutory product and
##      trivial intersection of the cyclic subgroups: the vertex-figure case
##      (q,m) = (5,5) is NOT excluded by "1/2 + 1/q + 1/m > 1" (that inequality
##      characterises finite triangle groups, not finite quotients).  The
##      resulting rank-3 group P(A5; a, b) is the great dodecahedron / small
##      stellated dodecahedron {5,5} with 12 vertices, 30 edges, 12 faces.
##  (b) Element orders of [3,3,5]^+ and of +-[O x O] (rotation subgroup of
##      [[3,4,3]]), used in the producer's Prop. E4 exclusions.
##  (c) In S4, two elements of order 4 with involutory product generate the same
##      cyclic group (so (q,m) = (4,4) is excluded by the intersection condition).
##  (d) Triangle-group check: for (q,m) in {(3,3),(3,4),(3,5)} the group
##      <a,b | a^q, b^m, (ab)^2> is finite of order 12, 24, 60; for (5,5) and
##      (4,4) it is infinite (so the producer's inequality is about these groups).
##  Run from audits/fable-ultra/scripts: gap -q -A --quitonbreak misc-audit.g < /dev/null
#############################################################################
Read("../../../gap/lib.g"); Read("../../../gap/polytopes.g"); PX.BuildAll(); PX.SetupRows();
SizeScreen([4096,]);
a := (1,2,3,4,5); b := (1,2,3,5,4);
H := Group(a, b);
Print("(a) a = ", a, ", b = ", b, ": orders ", [Order(a), Order(b)], ", ord(ab) = ", Order(a*b), ", <a> cap <b> trivial: ", IsTrivial(Intersection(Group(a), Group(b))),
      ", <a,b> = A5: ", H = AlternatingGroup(5), "; coset f-vector (V,E,F) of P(<a,b>; a, b) = ", [Index(H, Group(b)), Index(H, Group(a*b)), Index(H, Group(a))], "\n");
Print("    a and b lie in different A5-conjugacy classes of 5-cycles (rotation angles 2pi/5 and 4pi/5): ", not IsConjugate(H, a, b) and IsConjugate(H, a^2, b), "\n");
Print("AU-PASS  (a) the (5,5) vertex-figure case is realised in A5 and is not excluded by the spherical-triangle inequality\n");
## (d) finite triangle groups for the spherical pairs only (Size of an infinite fp group would not terminate);
##     for (5,5) the certificate is the explicit epimorphism onto A5 in (a)
for pr in [ [3,3],[3,4],[3,5] ] do
  F := FreeGroup("x","y"); x := F.1; y := F.2;
  Q := F/[x^pr[1], y^pr[2], (x*y)^2];
  Print("(d) triangle group <x,y | x^", pr[1], ", y^", pr[2], ", (xy)^2>: size ", Size(Q), "\n");
od;
F := FreeGroup("x","y"); x := F.1; y := F.2; Q := F/[x^5, y^5, (x*y)^2];
Print("(d) <x,y | x^5, y^5, (xy)^2> maps onto A5 (a -> (1,2,3,4,5), b -> (1,2,3,5,4)): ", GroupHomomorphismByImages(Q, AlternatingGroup(5), GeneratorsOfGroup(Q), [a, b]) <> fail, "\n");
## (c)
S4 := SymmetricGroup(4); four := Filtered(AsList(S4), g -> Order(g) = 4);
bad := Filtered(Cartesian(four, four), p -> Order(p[1]*p[2]) = 2 and IsTrivial(Intersection(Group(p[1]), Group(p[2]))));
Print("(c) pairs of order-4 elements of S4 with involutory product and trivial cyclic intersection: ", Length(bad), "\n");
if Length(bad) = 0 then Print("AU-PASS  (c) (q,m) = (4,4) is excluded in S4\n"); fi;
## (b)
T := PX.T.("{3,3,5}"); ps := PX.PermSetup(T.W);
Hp := Subgroup(ps.P, List([1..3], i -> ps.im(T.R[i]*T.R[i+1])));
Print("(b) |[3,3,5]^+| = ", Size(Hp), ", element orders ", Set(List(ConjugacyClasses(Hp), c -> Order(Representative(c)))), "\n");
Tc := PX.T.("{4,3,3}"); F4 := Group(Concatenation(Tc.R, [PX.Reflection([1,1,1,1])]));
Dm := (1/Sqrt(2))*[[1,1,0,0],[1,-1,0,0],[0,0,1,1],[0,0,1,-1]];
FF4 := Group(Concatenation(GeneratorsOfGroup(F4), [Dm]));
psF := PX.PermSetup(FF4); rot := Filtered(AsList(FF4), g -> DeterminantMat(g) = 1);
Print("(b) |[[3,4,3]]| = ", Size(FF4), ", rotation subgroup +-[OxO] of order ", Length(rot), ", element orders ", Set(List(rot, Order)), "\n");
Print("    p = 8 is an element order of [3,3,5]^+: ", 8 in Set(List(ConjugacyClasses(Hp), c -> Order(Representative(c)))), "; p in {5,15,20,30} are element orders of +-[OxO]: ",
      List([5,15,20,30], p -> p in Set(List(rot, Order))), "\n");
## (e) affine-to-linear lemma witness: S1 has no eigenvalue 1 on the effective 4-space for all ten families
for row in [1..10] do
  T := PX.T.(PX.Order[2*row-1]); S1 := T.R[1]*T.R[2]*T.R[4]*T.R[3];
  Print("(e) ", T.name, ": dim of fixed space of S1 in the ambient space = ", Length(NullspaceMat(S1 - IdentityMat(T.dim))), " (expected ", T.dim - 4, ")\n");
od;
Print("Done: misc-audit.g\n");
